2020-09-23 19:43:30.311 IST [6947] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-23 19:43:30.311 IST [6947] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-23 19:43:30.316 IST [6947] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-23 19:43:30.332 IST [6948] LOG:  database system was shut down at 2020-09-23 19:43:04 IST
2020-09-23 19:43:30.336 IST [6947] LOG:  database system is ready to accept connections
2020-09-23 19:44:13.670 IST [6982] ERROR:  database "myinner_db" already exists
2020-09-23 19:44:13.670 IST [6982] STATEMENT:  CREATE DATABASE myinner_db OWNER mynonsuperuser;
2020-09-23 20:10:47.548 IST [6947] LOG:  background worker "logical replication launcher" (PID 6954) exited with exit code 1
2020-09-23 20:10:47.548 IST [6947] LOG:  received smart shutdown request
2020-09-23 20:10:47.650 IST [6947] LOG:  received SIGHUP, reloading configuration files
2020-09-23 20:10:47.650 IST [6949] LOG:  shutting down
2020-09-23 20:10:47.681 IST [6947] LOG:  database system is shut down
2020-09-23 20:41:28.684 IST [5266] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-23 20:41:28.684 IST [5266] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-23 20:41:28.689 IST [5266] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-23 20:41:28.708 IST [5267] LOG:  database system was shut down at 2020-09-23 20:10:47 IST
2020-09-23 20:41:28.713 IST [5266] LOG:  database system is ready to accept connections
2020-09-23 21:19:39.436 IST [5266] LOG:  received smart shutdown request
2020-09-23 21:19:39.439 IST [5266] LOG:  background worker "logical replication launcher" (PID 5273) exited with exit code 1
2020-09-23 21:19:39.439 IST [5268] LOG:  shutting down
2020-09-23 21:19:39.445 IST [5266] LOG:  received SIGHUP, reloading configuration files
2020-09-23 21:19:39.464 IST [5266] LOG:  database system is shut down
2020-09-24 10:42:53.623 IST [6384] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-24 10:42:53.623 IST [6384] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-24 10:42:53.628 IST [6384] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-24 10:42:53.647 IST [6385] LOG:  database system was shut down at 2020-09-23 21:19:39 IST
2020-09-24 10:42:53.652 IST [6384] LOG:  database system is ready to accept connections
2020-09-24 12:40:21.382 IST [6384] LOG:  received smart shutdown request
2020-09-24 12:40:21.386 IST [6384] LOG:  background worker "logical replication launcher" (PID 6391) exited with exit code 1
2020-09-24 12:40:21.386 IST [6386] LOG:  shutting down
2020-09-24 12:40:21.396 IST [6384] LOG:  received SIGHUP, reloading configuration files
2020-09-24 12:40:21.413 IST [6384] LOG:  database system is shut down
2020-09-24 18:24:47.342 IST [6228] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-24 18:24:47.342 IST [6228] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-24 18:24:47.347 IST [6228] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-24 18:24:47.364 IST [6229] LOG:  database system was shut down at 2020-09-24 12:40:21 IST
2020-09-24 18:24:47.370 IST [6228] LOG:  database system is ready to accept connections
2020-09-24 20:02:45.952 IST [6228] LOG:  received smart shutdown request
2020-09-24 20:02:45.955 IST [6228] LOG:  background worker "logical replication launcher" (PID 6235) exited with exit code 1
2020-09-24 20:02:45.955 IST [6230] LOG:  shutting down
2020-09-24 20:02:45.971 IST [6228] LOG:  received SIGHUP, reloading configuration files
2020-09-24 20:02:45.981 IST [6228] LOG:  database system is shut down
2020-09-24 20:19:02.691 IST [5392] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-24 20:19:02.691 IST [5392] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-24 20:19:02.696 IST [5392] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-24 20:19:02.715 IST [5393] LOG:  database system was shut down at 2020-09-24 20:02:45 IST
2020-09-24 20:19:02.721 IST [5392] LOG:  database system is ready to accept connections
2020-09-24 20:37:44.972 IST [5392] LOG:  received smart shutdown request
2020-09-24 20:37:44.998 IST [5392] LOG:  background worker "logical replication launcher" (PID 5399) exited with exit code 1
2020-09-24 20:37:44.998 IST [5392] LOG:  received SIGHUP, reloading configuration files
2020-09-24 20:37:45.000 IST [5394] LOG:  shutting down
2020-09-24 20:37:45.051 IST [5392] LOG:  database system is shut down
2020-09-25 10:59:46.896 IST [7629] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-25 10:59:46.896 IST [7629] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-25 10:59:46.901 IST [7629] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-25 10:59:46.920 IST [7630] LOG:  database system was shut down at 2020-09-24 20:37:45 IST
2020-09-25 10:59:46.925 IST [7629] LOG:  database system is ready to accept connections
2020-09-25 12:44:02.945 IST [7629] LOG:  received smart shutdown request
2020-09-25 12:44:02.955 IST [7629] LOG:  received SIGHUP, reloading configuration files
2020-09-25 12:44:02.984 IST [7629] LOG:  background worker "logical replication launcher" (PID 7636) exited with exit code 1
2020-09-25 12:44:02.984 IST [7631] LOG:  shutting down
2020-09-25 12:44:03.065 IST [7629] LOG:  database system is shut down
2020-09-25 18:27:34.358 IST [4565] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-25 18:27:34.359 IST [4565] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-25 18:27:34.363 IST [4565] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-25 18:27:34.382 IST [4566] LOG:  database system was shut down at 2020-09-25 12:44:03 IST
2020-09-25 18:27:34.387 IST [4565] LOG:  database system is ready to accept connections
2020-09-25 18:53:00.928 IST [6085] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:53:00.928 IST [6085] DETAIL:  Key (username)=(projects) already exists.
2020-09-25 18:53:00.928 IST [6085] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$mkqvYIigu9Ua$lhYq8gKfTk22MLivP9q574v8Yri6aFsyfv2UWs0L/k0=', NULL, false, 'projects', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:23:00.755280+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:53:02.452 IST [6087] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:53:02.452 IST [6087] DETAIL:  Key (username)=(projects) already exists.
2020-09-25 18:53:02.452 IST [6087] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$ElSb76iOfmKu$3Eh9GitNZk6fJOX24LrOeVhJeOfILZ5HyBg6JpuTbVM=', NULL, false, 'projects', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:23:02.303286+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:53:03.743 IST [6088] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:53:03.743 IST [6088] DETAIL:  Key (username)=(projects) already exists.
2020-09-25 18:53:03.743 IST [6088] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$ZapM4yWculjA$WbFsC30W98UQEuUp4zvkpFASlGTRB73hf/MxG+i2gLw=', NULL, false, 'projects', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:23:03.571731+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:53:53.512 IST [6096] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:53:53.512 IST [6096] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:53:53.512 IST [6096] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$8ebw3MwvRrUJ$kGuGf6TUSIKZ6luEQfq0dQo8qDaiRS1VEViJNkle0Eo=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:23:53.364393+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:53:53.932 IST [6098] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:53:53.932 IST [6098] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:53:53.932 IST [6098] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$JyFbuWm8ApBT$pjs8a2+/JAuuOa7h5pldNIGsR+jlfeh2pVI6fmXEjr0=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:23:53.781900+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:53:54.891 IST [6099] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:53:54.891 IST [6099] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:53:54.891 IST [6099] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$ybaBoAbsQM3s$jp/fspsUor7qSMMb0X0kSURHbl6s9vdapntIZTRb7zg=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:23:54.739618+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:53:55.264 IST [6100] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:53:55.264 IST [6100] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:53:55.264 IST [6100] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$XMi4A2Lg0kTH$zlXzRP0fqX4I85/qmaNB7gudaSvfj29Y/wk3zvRxK0Q=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:23:55.112302+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:06.318 IST [6102] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:06.318 IST [6102] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:06.318 IST [6102] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$wV5pnm66jW3e$PN8xDTjeCkNfFB1uDsG8EFY6S5gfOgA/6I/xNp5iCJo=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:06.164943+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:07.336 IST [6103] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:07.336 IST [6103] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:07.336 IST [6103] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$7azYBp04YkpX$SfH5lzUee8zGnisaKL8ngxjbKOLn703YQIn6hJ2SFO0=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:07.180005+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:07.697 IST [6104] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:07.697 IST [6104] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:07.697 IST [6104] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$adQeiAZ3iSXd$UBIWEwvUa929CyDhx9fonM9XS082dMJfQHXhFkcP6No=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:07.545827+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:07.972 IST [6105] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:07.972 IST [6105] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:07.972 IST [6105] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$z0168SH1gkeA$SOtzK1awAQwn8K5532ed9YJxsLAiDi7dnE1mcbNlgQg=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:07.821581+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:08.300 IST [6106] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:08.300 IST [6106] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:08.300 IST [6106] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$Qmo2cYvBAhIP$S1aDEHVTBrvk7Eh1ADOUc/6VMWgwDb/n8I/l1Ww8H5Q=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:08.131799+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:10.837 IST [6107] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:10.837 IST [6107] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:10.837 IST [6107] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$d4YW7Ian2Fx7$6BuW86dk2H5HFBAmpbT6SMlYcjsMUMZMPbUq73Kn8EQ=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:10.679904+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:11.028 IST [6109] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:11.028 IST [6109] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:11.028 IST [6109] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$f9whbNwrt1YP$Fl24uWv6Xq5NGYYXpXo8J/0WfKO9JqsYYzYuwAWqu34=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:10.844320+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:11.123 IST [6110] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:11.123 IST [6110] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:11.123 IST [6110] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$u7hiIYtWeTF1$E5HpdjsEdFaeBC7dS7DYGSn5cvlhjUWAmg9VDC0H+Xo=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:10.938215+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:11.379 IST [6111] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:11.379 IST [6111] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:11.379 IST [6111] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$d2gh0u30yJFr$FJdCZyLKC2Lptuf7KQCqz5sQGVj01mphwK9XCnWpfxE=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:11.183886+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:11.542 IST [6112] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:11.542 IST [6112] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:11.542 IST [6112] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$r1nUo1pYVtgB$A6ERXkF3vsrUOigTHJrh0loWXTMVMFoTRbfLVxK//Vo=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:11.387100+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:20.329 IST [6115] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:20.329 IST [6115] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:20.329 IST [6115] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$iNafBUkFvlNO$SeNG8vHI0Wl1xpt32VGtMU2nedeD2oTEjmMumhLZEW0=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:20.162798+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:20.573 IST [6116] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:20.573 IST [6116] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:20.573 IST [6116] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$WGal3qj62RwA$QrAeJacFmXjpALOaJWcA0CR3TLt2WZINxQ12KXzkstI=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:20.419118+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:20.848 IST [6117] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:20.848 IST [6117] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:20.848 IST [6117] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$pjF7JjYnXPL3$Ivg0Xnq322xUT2GK/CD+PdtdM4/IJv4EweMNrab1lKk=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:20.670919+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:21.118 IST [6118] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:21.118 IST [6118] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:21.118 IST [6118] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$MyNaSgJ7pFJw$BZPWs4lY1/SIW7g2iktbolABoH7lrrTemyVW7Gzluis=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:20.964610+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:21.414 IST [6119] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:21.414 IST [6119] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:21.414 IST [6119] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$V5vuz8ot5G1e$Kw0S3vjGg/1VMvS29Ig0mTcqyEcN/G/TLr4AqIOBFr0=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:21.241515+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:21.663 IST [6120] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:21.663 IST [6120] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:21.663 IST [6120] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$LMhWvgA18NNc$52wMLWjJgUz7NWWSEKifcHaEGzqgkU5uUT1CytC2bdY=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:21.504376+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:25.743 IST [6124] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:25.743 IST [6124] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:25.743 IST [6124] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$imPCPemNLlxU$7RoVMhy1zVd7OUhDJVe1lrwbIWGpXp5Fzv/qCcAS3Ww=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:25.595732+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:26.304 IST [6125] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:26.304 IST [6125] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:26.304 IST [6125] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$U1AHIixmzPue$n1jkIs3DaIp+rFPL5BiY1Ry6F1z8M8fB/cvM8LPAF/c=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:26.156008+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:26.838 IST [6126] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:26.838 IST [6126] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:26.838 IST [6126] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$hAwhlj0uj4zU$s6gE2/1omEmnLyPB3qSeMKnVt6901DRSOoKrvxh4mbg=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:26.658003+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:27.129 IST [6127] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:27.129 IST [6127] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:27.129 IST [6127] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$fvfJoWiSKmFh$hKjtF+CJhpq9tIdkmfz8vfzWXOz7C+2+Ox/EP8Qo1YQ=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:26.893990+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:29.189 IST [6128] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:29.189 IST [6128] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:29.189 IST [6128] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$ZjhMCR1t8yIc$TYY8WQ9++crziF1crVcpIxXj01NWLXDE0Ch8Abitzig=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:29.013180+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:29.450 IST [6129] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:29.450 IST [6129] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:29.450 IST [6129] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$VAwMh7GsyH6Y$ULJDY31P7z0Tdvq3bCIk8OiipVBk3VsvRx6SNJebnCk=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:29.256454+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:30.385 IST [6130] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:30.385 IST [6130] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:30.385 IST [6130] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$oNlNgvgpLREz$b+5KzrxolEBmypjqrlD1yAB4sIjLCzTaX1JA1FPtDN4=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:30.202635+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:32.587 IST [6131] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:32.587 IST [6131] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:32.587 IST [6131] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$98h5WTh5c4Br$FQOao1hvpqklDrRh3pfwjd0LjcwpYjfMTfAuO/lOj98=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:32.434485+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:32.782 IST [6132] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:32.782 IST [6132] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:32.782 IST [6132] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$JwhXxF13uL68$eo7rkOMfgiEPKooEKtze5WwWoi3TJoNRle4s7FJiIXI=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:32.630379+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:35.719 IST [6134] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:35.719 IST [6134] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:35.719 IST [6134] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$iHATVcpgKlnk$GdIpv9TfECUziBounXZ/3n60HG7mpbG6EAYj6O5qVXs=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:35.534839+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:35.960 IST [6135] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:35.960 IST [6135] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:35.960 IST [6135] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$GInBSsueyLML$E0cYjHfunRbA7p8bhjiyC+m3HpJi6I+ao3teVvKTMQU=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:35.785747+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:38.826 IST [6136] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:38.826 IST [6136] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:38.826 IST [6136] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$qAMPg3zJ2Zok$gCdWKB6FBX0v/9Hct8WJhhDAfSsufp3kQXz02LlSclY=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:38.674328+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:42.229 IST [6137] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:42.229 IST [6137] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:42.229 IST [6137] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$NuWdWn6TTgOW$a8ntQPAnYxALEq0gt9UrUjkY0r3ykVpVTZLN0Ebhwok=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:42.052536+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:45.273 IST [6140] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:45.273 IST [6140] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:45.273 IST [6140] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$dn3fD536uEeJ$LfR/vTsPZjHvjQP4pzpeHM4kxK8d50fuE5pNufs4/50=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:45.123576+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:48.668 IST [6141] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:48.668 IST [6141] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:48.668 IST [6141] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$Hnoh9skCcn8L$98WgmlWXJpx7T3go4LDezwtrOIz/jJA0SAEU2gJVVUc=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:48.515272+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:49.254 IST [6142] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:49.254 IST [6142] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:49.254 IST [6142] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$SRjpMycHr2C2$V98JTD2ophJia8aWZ/YIUrpKQ6pwcRD9EoZEN7dQ3BU=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:49.089993+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:49.475 IST [6143] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:49.475 IST [6143] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:49.475 IST [6143] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$oWyZXv1yC9d8$ENzfp1JDOLXoKfY6Z9XSPCsP+N+lYNuEEhZHvnY/5hA=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:49.319132+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:49.738 IST [6144] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:49.738 IST [6144] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:49.738 IST [6144] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$0bUaa5tf8NVJ$gS/SuvRDaomDsWL4lqLceAbQqoKEmJxw+dmZEAnY9Nc=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:49.553313+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:54:49.952 IST [6145] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:54:49.952 IST [6145] DETAIL:  Key (username)=(Judson) already exists.
2020-09-25 18:54:49.952 IST [6145] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$uZFkE4YTCmjc$z6re3cGFi1G3D2BcrzqFx1qMhJFVPx2QaTcaegqMA60=', NULL, false, 'Judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:24:49.794258+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:31.559 IST [6272] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:31.559 IST [6272] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:31.559 IST [6272] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$EJmVNvt51BJH$aM4m61pJF/alaXuP07gRGud/w4sTg+tbSjfMDBofe1c=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:31.411107+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:32.109 IST [6274] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:32.109 IST [6274] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:32.109 IST [6274] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$UVVaUc9geVMc$LmiEXp3zNCU84ogTN+Uq6CuqSUQN02qiPdaRsNYyznE=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:31.959204+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:32.957 IST [6275] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:32.957 IST [6275] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:32.957 IST [6275] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$aFq9CKCjjj77$zxRug9VMBTGa0DnTw+OZhCqve+sg+8kDovS4GpaGklw=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:32.794923+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:33.210 IST [6276] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:33.210 IST [6276] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:33.210 IST [6276] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$2JG8fg3bq4Ol$ksTtl7eimYhtu1Ns4/mjPe92dDkBtfzxZjBP7uVhuFo=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:33.059956+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:43.997 IST [6278] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:43.997 IST [6278] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:43.997 IST [6278] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$OVgMUYcz57Tq$JgtOEli1546PbjTJbglsOPgu/k+s3uCi06TymBynKTI=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:43.846630+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:44.811 IST [6279] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:44.811 IST [6279] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:44.811 IST [6279] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$R3LTOnMw53mG$+7xzTx1aJz3MKIoGPe8QVtHii9n1D9BM/8t7chjhIQM=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:44.656357+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:45.071 IST [6280] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:45.071 IST [6280] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:45.071 IST [6280] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$2iVP7AIaLoav$WubK0DgbYGEIufX2vhaa9eA2lOKFK7FL8e7tXaOocE8=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:44.916607+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:45.309 IST [6281] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:45.309 IST [6281] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:45.309 IST [6281] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$VldlXZr8V6Pa$ISiN/RvKYK03uqcP+77TtuNXAHNP/OYn9c2mrDAz3fo=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:45.150559+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:45.697 IST [6282] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:45.697 IST [6282] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:45.697 IST [6282] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$HOipAEK8mD4Q$17mjI5LUeQr8ZEF4vjhBqJIAjPCQW1257oEGfTgkQv8=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:45.531093+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:46.674 IST [6283] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:46.674 IST [6283] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:46.674 IST [6283] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$XbKGeN2oHJSL$ehpCIud3mwHJ3FGT6Jc2EZAYQzmi59EvDOJ0wEhk76M=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:46.506137+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:55.522 IST [6284] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:55.522 IST [6284] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:55.522 IST [6284] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$qyorlxUMQy7h$F9If816h+ttb63gdfrz4fPeCKktQ1tgW8N0didkazOM=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:55.374529+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:55.769 IST [6285] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:55.769 IST [6285] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:55.769 IST [6285] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$wNpWTsVNwDre$JcLHFzFJIba7+GmaikzIRy2QbbqIodaGNEowrKxEqgE=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:55.595734+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:56.209 IST [6286] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:56.209 IST [6286] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:56.209 IST [6286] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$F9wFzIy4OWXh$66jVuUfb6c/czWzZC00eF0m+VgRT9PdlGAGwegIfC48=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:56.050727+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:56.499 IST [6287] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:56.499 IST [6287] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:56.499 IST [6287] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$eIyI0RGxTzVT$EQUobJBmJzT4BnEvw4OhWAN/Y82HdDqcX8P4Ev3pS+Q=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:56.327181+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:58:58.690 IST [6290] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:58:58.690 IST [6290] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:58:58.690 IST [6290] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$0bv7UYJ9BpJt$DrvKvbSfSwfCGchnUX49kh8+ad3wnEAo6ynFog0EmB0=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:28:58.509352+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:09.004 IST [6293] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:09.004 IST [6293] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:09.004 IST [6293] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$xVrZ8d8qAtfv$KqvIZ5yMLqSutIe2AIyp8lq7n6AAXlB4xA4+WHkY1zk=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:08.832469+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:09.309 IST [6294] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:09.309 IST [6294] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:09.309 IST [6294] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$2WlyezwxogFl$YhYMaG1HqDjbJgcLqf6V93s10t/ijdIZ+fGTdij9bZA=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:09.138226+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:09.679 IST [6295] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:09.679 IST [6295] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:09.679 IST [6295] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$zpc4bDDyjBv1$3Dtxz3IzoQi31S3R2Dl+AWAM7rXVRMA9epUOoebiWcM=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:09.514880+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:09.911 IST [6296] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:09.911 IST [6296] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:09.911 IST [6296] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$KkMi1ELYRb2o$+k71tz5etwpZgrXhtUrLKrN2l33EibOzXPYxPIEL47Q=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:09.742132+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:17.917 IST [6297] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:17.917 IST [6297] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:17.917 IST [6297] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$O47m0DjFeLpC$VdXWHHAAob/dhAfbTMO3W3eVX/Xmw1rlM7VQ1bc3Mlw=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:17.744175+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:18.711 IST [6298] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:18.711 IST [6298] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:18.711 IST [6298] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$bKR5mDGmhnMr$fCnIxVdCbJh3rpeJjpoXx4I6x8iQHV8+SrS/4CLOlAQ=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:18.530268+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:18.966 IST [6299] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:18.966 IST [6299] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:18.966 IST [6299] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$teLZKB7hxicV$bbbc7wrYDCIUCMiTpkkkKGvA39iZ8BuiQenmcwTGq/g=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:18.785949+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:19.191 IST [6300] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:19.191 IST [6300] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:19.191 IST [6300] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$IUZMGhg2sYJc$FXxW2v1xC1K93mOwZMEbtyUpNyVpbBvO7F6yrCDJewU=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:19.018229+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:24.634 IST [6304] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:24.634 IST [6304] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:24.634 IST [6304] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$sxn0RBwPP6Ki$fgVyyHLWQsXXlhf9Eps1Oz+8gF1HG6dqAgK3rrF/iTg=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:24.481569+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:24.975 IST [6305] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:24.975 IST [6305] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:24.975 IST [6305] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$i6ojJUvcrogu$GIVsqYz9KzZ0+8Q+j+dqOTdBkAhj3p2mmEAPQBkdua0=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:24.813944+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:25.334 IST [6306] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:25.334 IST [6306] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:25.334 IST [6306] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$TPXrFVPndfzd$fNoNMUPfRmJ2yjRB2fDOLKJ/pPVFL4yShh672a+DTxE=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:25.178412+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:25.674 IST [6307] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:25.674 IST [6307] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:25.674 IST [6307] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$765tV79j3QxI$p9/DiQfqvq5xmDajTci2GFT9+++fwUR0PHTEWOezUI4=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:25.502452+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:28.958 IST [6309] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:28.958 IST [6309] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:28.958 IST [6309] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$ASlKcEvFhfqM$58P+H0BEWWzx3ivYVYmOZ2XoyDXbg1VqY9CsSZ6CNR8=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:28.790056+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:31.618 IST [6310] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:31.618 IST [6310] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:31.618 IST [6310] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$6pUGwG78Huzu$hVwwcenPVnk752NvaYkISQUSajUVJ5Ao5qSEULfkUeU=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:31.445297+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:33.977 IST [6311] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:33.977 IST [6311] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:33.977 IST [6311] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$YPpjDUVrOH9u$uRFLCHYELT/Q0JdWMF1qiipgU9xLeS1P8oW0nJkr4WY=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:33.810408+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 18:59:34.434 IST [6312] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 18:59:34.434 IST [6312] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 18:59:34.434 IST [6312] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$EZRjvwPPs1DM$X9XYl7Laya5ECCe0p5r4ERinF+UZAgV2CXO+2G2POZo=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T13:29:34.280496+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:15.869 IST [9354] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:15.869 IST [9354] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:15.869 IST [9354] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$KDnd1vQLce3H$XF2uBZHJOJs54rqsuNudfn0rgPhyvTyt27dxtT5Adh8=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:15.709197+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:20.248 IST [9357] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:20.248 IST [9357] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:20.248 IST [9357] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$uINl1rYIuopc$59YJkgTI+fPMGzt8pDkf+C1VmSPqZXf/PtjsISCLRzs=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:20.075584+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:20.474 IST [9360] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:20.474 IST [9360] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:20.474 IST [9360] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$hW4AOwodF5mQ$ZWFC/m9VewA3/mNRxXkiBYMWMUOLV8lzZDWmPKSdXt0=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:20.306159+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:20.480 IST [9361] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:20.480 IST [9361] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:20.480 IST [9361] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$5b1GqYzNEUFx$MtESDfrg2od+11g2A+Y9I1vYGscmPtfCQmWdJqVeoX4=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:20.212585+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:22.091 IST [9362] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:22.091 IST [9362] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:22.091 IST [9362] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$QH6eBdinVIuj$Gb2TQgiuuWqsSxJGmwPSMmKQaF+x191lIsiW0rSlzC4=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:21.935998+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:38.352 IST [9367] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:38.352 IST [9367] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:38.352 IST [9367] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$v2eOcyR9zq6V$XVRBzDBjFbynzo2aQeoBgxsSxRF5lDaj1BsfWCPa3is=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:38.203063+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:39.952 IST [9368] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:39.952 IST [9368] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:39.952 IST [9368] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$qU5YkkfJQTmX$EEGtI4nkWojC+T/rkeiPowbI2fQTb7zvNa/Gita44pU=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:39.776791+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:03:40.164 IST [9369] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:03:40.164 IST [9369] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:03:40.164 IST [9369] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$OJJEp4u5xPqi$McWpdFbqIpbYv1gUqWm8fLO0sT2fZuWvfdHPwkLNmYA=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:33:40.007429+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:04:06.283 IST [9371] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:04:06.283 IST [9371] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:04:06.283 IST [9371] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$DrQrih0cFYOO$lZNE7RwwKZHM98LSnEcwFcpNjAxioULE2+INGP/EbNQ=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:34:06.124011+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:04:17.871 IST [9374] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:04:17.871 IST [9374] DETAIL:  Key (username)=(o.judsonleo) already exists.
2020-09-25 20:04:17.871 IST [9374] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$LOGIIMVMT5ma$nqvP8H2VoHdPRD6kBQI+m3OpnvMHDu/A9FQhAgFkFgI=', NULL, false, 'o.judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:34:17.718224+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:04:34.245 IST [9379] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:04:34.245 IST [9379] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-25 20:04:34.245 IST [9379] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$4zvph59yqMn3$uZ8DlGvsKlgfkNaai4vbM/+Tl2ouNoa2RFgoIpX7qBY=', NULL, false, 'judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:34:34.081531+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:04:35.432 IST [9380] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:04:35.432 IST [9380] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-25 20:04:35.432 IST [9380] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$HOvZDB1RN7FJ$gRi34Cf9exVS0RxFgfqzfM5lraT1Hcn67w7DwLuuzbI=', NULL, false, 'judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:34:35.250245+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:04:54.407 IST [9382] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:04:54.407 IST [9382] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-25 20:04:54.407 IST [9382] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$USn0rn4StSES$2Ig9eDG5Pa70+NwJqoaBxe8wvhAnX5f/jMXkbvcWcT4=', NULL, false, 'judsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-25T14:34:54.251830+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:04:55.432 IST [9383] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:04:55.432 IST [9383] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-25 20:04:55.432 IST [9383] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$TCsV6b4uLGXh$/1C9IaGoM9QjAOgIXPlQ+l/V8f3ub5FKvjtGrTX7DJ0=', NULL, false, 'judsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-25T14:34:55.264571+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:06:51.195 IST [9401] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:06:51.195 IST [9401] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:06:51.195 IST [9401] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$9Gj1LIE3eS7Q$1RNXl0E55XFYzS5eTQsIUY6nWz1zDjZKEciIdxJ0NQQ=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:36:51.051649+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:06:54.226 IST [9404] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:06:54.226 IST [9404] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:06:54.226 IST [9404] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$jtQRJvgZWSnA$GuxulPdoUtNI3lM58fM4hPrvpaNb0pzv3HhFGV9PObU=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:36:54.083437+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:07:00.873 IST [9406] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:07:00.873 IST [9406] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:07:00.873 IST [9406] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$pq0QrmJVyRYU$e+Iaw9LImyHiSXhOONqIE5SMbvQbcyL3ssfCvnvnZXI=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:37:00.728790+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:07:01.912 IST [9407] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:07:01.912 IST [9407] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:07:01.912 IST [9407] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$3xCXWdeGVEFh$nqBAVbkZoSTmOF4XZPx+SvDGS8G+mu9eOfZOGCNjlYk=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:37:01.761725+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:07:17.621 IST [9411] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:07:17.621 IST [9411] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:07:17.621 IST [9411] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$4Bj3rzkyOqDl$WCREPu4FoDlzTu0uWHfWzKFuvQhJctlRUXEYz4wDmZ0=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:37:17.469499+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:07:17.856 IST [9413] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:07:17.856 IST [9413] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:07:17.856 IST [9413] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$MpMTLPvzaSyI$57x+zLsVccmOx5qQkOTe9CO7tMY7xCGBeugfW8d77Mo=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:37:17.708801+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:07:18.204 IST [9414] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:07:18.204 IST [9414] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:07:18.204 IST [9414] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$SD1rSezRUIKV$pNMhacCaEO/NSjLxN2XLKVWVoLW+cFBxNTXPc9R+Zjw=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:37:18.061656+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:07:42.460 IST [9430] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:07:42.460 IST [9430] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:07:42.460 IST [9430] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$00W3X84jhmyL$w7mmDc1wE/xikZLnuZllz2K0rx1B+qNAbgxeSei3iQo=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:37:42.315822+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:07:43.412 IST [9431] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-25 20:07:43.412 IST [9431] DETAIL:  Key (username)=(leo) already exists.
2020-09-25 20:07:43.412 IST [9431] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$Lo7wHcUupdqg$TzZrCYmXWGjAzQJ1cmPpjlne1SXhd3nLXDjIwH8BELM=', NULL, false, 'leo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-25T14:37:43.269595+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-25 20:09:49.618 IST [4565] LOG:  received smart shutdown request
2020-09-25 20:09:49.739 IST [4565] LOG:  background worker "logical replication launcher" (PID 4572) exited with exit code 1
2020-09-25 20:09:49.741 IST [4565] LOG:  received SIGHUP, reloading configuration files
2020-09-25 20:09:49.743 IST [4567] LOG:  shutting down
2020-09-25 20:09:49.778 IST [4565] LOG:  database system is shut down
2020-09-26 10:34:35.363 IST [5534] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-26 10:34:35.364 IST [5534] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-26 10:34:35.368 IST [5534] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-26 10:34:35.387 IST [5535] LOG:  database system was shut down at 2020-09-25 20:09:49 IST
2020-09-26 10:34:35.393 IST [5534] LOG:  database system is ready to accept connections
2020-09-26 12:53:50.417 IST [5534] LOG:  received smart shutdown request
2020-09-26 12:53:50.422 IST [5534] LOG:  background worker "logical replication launcher" (PID 5541) exited with exit code 1
2020-09-26 12:53:50.423 IST [5536] LOG:  shutting down
2020-09-26 12:53:50.439 IST [5534] LOG:  received SIGHUP, reloading configuration files
2020-09-26 12:53:50.453 IST [5534] LOG:  database system is shut down
2020-09-26 13:19:52.651 IST [3529] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-26 13:19:52.652 IST [3529] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-26 13:19:52.657 IST [3529] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-26 13:19:52.676 IST [3530] LOG:  database system was shut down at 2020-09-26 12:53:50 IST
2020-09-26 13:19:52.682 IST [3529] LOG:  database system is ready to accept connections
2020-09-26 13:45:35.651 IST [3529] LOG:  received smart shutdown request
2020-09-26 13:45:35.656 IST [3529] LOG:  background worker "logical replication launcher" (PID 3536) exited with exit code 1
2020-09-26 13:45:35.656 IST [3531] LOG:  shutting down
2020-09-26 13:45:35.669 IST [3529] LOG:  received SIGHUP, reloading configuration files
2020-09-26 13:45:35.704 IST [3529] LOG:  database system is shut down
2020-09-26 18:47:58.910 IST [6695] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-26 18:47:58.911 IST [6695] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-26 18:47:58.916 IST [6695] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-26 18:47:58.935 IST [6696] LOG:  database system was shut down at 2020-09-26 13:45:35 IST
2020-09-26 18:47:58.940 IST [6695] LOG:  database system is ready to accept connections
2020-09-26 19:09:21.361 IST [7095] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:09:21.361 IST [7095] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:09:21.361 IST [7095] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$VtSm5l2ewejJ$tMHV7N8wtbRBe4snAsVGvFOp75qyyvJ80w/HyXR6BHs=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:39:21.213062+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:09:34.638 IST [7100] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:09:34.638 IST [7100] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:09:34.638 IST [7100] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$qvK0n8DVoIjW$p1vUpGEYB8HNWpb/vDZb7Ym1IamtdBWddKQ3G0+rP74=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:39:34.495317+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:09:43.993 IST [7101] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:09:43.993 IST [7101] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:09:43.993 IST [7101] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$FISKevybBnjn$gT9dry2pyoCtczAKtKl2kqGtTKgmMvABygCt9MJpI2E=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:39:43.836616+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:11:29.043 IST [7116] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:11:29.043 IST [7116] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:11:29.043 IST [7116] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$6QZPLlq975Zw$ZZmvUNSdMYTm2Wq84FAMSKz9ed4vsGTH6UATOoR5j08=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:41:28.895147+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:12:39.421 IST [7129] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:12:39.421 IST [7129] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:12:39.421 IST [7129] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$oitYlPAhPlyY$lE8WJZpqQJwFZEl+K4PmX/32uQxLcBb1+7yJsXEUBmc=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:42:39.273432+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:12:50.929 IST [7136] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:12:50.929 IST [7136] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:12:50.929 IST [7136] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$KO9K2E8tk5X6$nhnZ0lTz8KQrCYxxHHCR4Er+SYepnE9dvrzEfbNV2t8=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:42:50.782272+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:13:05.072 IST [7141] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:13:05.072 IST [7141] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:13:05.072 IST [7141] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$b4z7tJly8VbQ$dBPmUwU2qi+HaRLe/hkik1Pm15T1e0bUjxkNOv1kkIw=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:43:04.921290+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:13:46.551 IST [7147] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:13:46.551 IST [7147] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:13:46.551 IST [7147] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$hZ2NwZMnFfHB$Ey9BdQ1BrVFUF/GTcp/pt8VeRolFYHp6yaXc3GVAp9M=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:43:46.405539+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:13:56.509 IST [7153] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:13:56.509 IST [7153] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-26 19:13:56.509 IST [7153] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$cOen7n9H7EgC$s4jzqJNSqN6MG50VisIQp9KYWScY0BAOKPT91xuGD8w=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-26T13:43:56.366561+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:20.011 IST [7216] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:20.011 IST [7216] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:20.011 IST [7216] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$e7SwidMPNtpH$kirEMgFAf04qPzKLkq4IMt/HFdiQcDe6EmU6fXsHfdo=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:19.858391+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:30.487 IST [7220] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:30.487 IST [7220] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:30.487 IST [7220] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$ZsgZJwotZsZW$8VjTx9xyurLI434Q6RwNTdFcQkZl4ptqwtEwtAcRZuA=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:30.319906+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:31.355 IST [7222] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:31.355 IST [7222] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:31.355 IST [7222] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$IENzz2LRlyJx$wG0XRWTu0xjMsBCrLB+Yv9yAdywwA+pwf7fuMaMIBN8=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:31.199002+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:43.756 IST [7223] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:43.756 IST [7223] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:43.756 IST [7223] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$EusDi74tiSmE$8ihqUgscw1azkGGKZbgBHwdUZy1x4DmFIyQNfHFH33s=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:43.605352+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:45.095 IST [7224] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:45.095 IST [7224] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:45.095 IST [7224] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$X4uri83JFvg8$CrJWJrmhIDwo+7+gywIP/aFbFsgklWOH7FYm8VlJKfc=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:44.947520+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:52.179 IST [7226] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:52.179 IST [7226] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:52.179 IST [7226] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$kA9NR9xhKUAW$moeyfYo0euLYiE8t2wMk8AgfB8QImKZdikOU1Z3DOl4=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:52.027903+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:52.956 IST [7229] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:52.956 IST [7229] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:52.956 IST [7229] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$gBvTnEjR4Zq6$lSvCf0lK7gBhKaDVz0u+mXynkvUDqfm6jmV6gCzVvzc=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:52.791917+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:53.238 IST [7230] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:53.238 IST [7230] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:53.238 IST [7230] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$4fHZk8q2oAC4$xGpWC1HMcLZAlXJGs89BGsz+zWhvKhyDaA7rP62vMDM=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:53.086642+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:53.540 IST [7231] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:53.540 IST [7231] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:53.540 IST [7231] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$RRIV4M0tEaPx$hv6y/m6CZUWTHmnBxSkvf17YDKJSkRw/Keo3rlCYBAQ=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:53.388346+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:20:59.095 IST [7234] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:20:59.095 IST [7234] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:20:59.095 IST [7234] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$fRHCRC10mlxW$kG+bVUsO9dxjGQKf+RdBY7mVyumjX/o6Yjsvv67psrA=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:50:58.940458+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:21:00.242 IST [7236] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:21:00.242 IST [7236] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-26 19:21:00.242 IST [7236] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$j4jdxrOdRGeR$w5tAlUcnXN+DiuKW6RANEV0TuxbtOvmVMV5MNmVGWAU=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-26T13:51:00.090679+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:21:49.982 IST [7240] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:21:49.982 IST [7240] DETAIL:  Key (username)=(obedotto) already exists.
2020-09-26 19:21:49.982 IST [7240] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$YdQq7vSXKneZ$lkewFgcWcv++Z5it3WVVLP817t9D4n25/TUiKXZmEJY=', NULL, false, 'obedotto', '', '', 'obedotto@gmail.com', false, true, '2020-09-26T13:51:49.830548+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:22:49.417 IST [7250] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:22:49.417 IST [7250] DETAIL:  Key (username)=(admin) already exists.
2020-09-26 19:22:49.417 IST [7250] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$f5CMNPzGaLI5$Bl8EOMaUKtbqEtwV10wGOCLNonr5il4/mFa2hujCLDI=', NULL, false, 'admin', '', '', 'admin@gmail.com', false, true, '2020-09-26T13:52:49.226636+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:23:14.764 IST [7257] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:23:14.764 IST [7257] DETAIL:  Key (username)=(admin) already exists.
2020-09-26 19:23:14.764 IST [7257] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$sHzr43rSI3VW$r6l5Xj4+Z3e0w8oMDH421cvZ2gJe5d+CU5ZeeugpF4Y=', NULL, false, 'admin', '', '', 'admin@gmail.com', false, true, '2020-09-26T13:53:14.603238+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 19:23:23.680 IST [7258] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-26 19:23:23.680 IST [7258] DETAIL:  Key (username)=(admin) already exists.
2020-09-26 19:23:23.680 IST [7258] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$iHjwldjRxILj$t0Yh8Ka+WdsW8xBh+lodjmeo29Q6l+zUPQ7O2KhWRKo=', NULL, false, 'admin', '', '', 'admin@gmail.com', false, true, '2020-09-26T13:53:23.507452+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-26 21:09:29.345 IST [6695] LOG:  received smart shutdown request
                                                                                                                                                                                                                                                                                                                                                  2020-09-27 10:45:25.029 IST [4681] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-27 10:45:25.030 IST [4681] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-27 10:45:25.034 IST [4681] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-27 10:45:25.053 IST [4682] LOG:  database system was shut down at 2020-09-26 21:09:29 IST
2020-09-27 10:45:25.059 IST [4681] LOG:  database system is ready to accept connections
2020-09-27 10:45:25.059 IST [4687] LOG:  corrupted statistics file "pg_stat/global.stat"
2020-09-27 11:03:23.482 IST [6332] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:03:23.482 IST [6332] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 11:03:23.482 IST [6332] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$ggRQQ4XWSdac$FaY3gp3j7T+zs5BY3tOVSHhCgwG9RdDA8EsFrW+9Otg=', NULL, false, 'judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T05:33:23.316411+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:03:45.884 IST [6347] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:03:45.884 IST [6347] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 11:03:45.884 IST [6347] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$iDf9qhV4Yzxg$GvOocDy4XDPe9ulDSvZXHNwBbG0k/PpNup2pnax6uMI=', NULL, false, 'judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T05:33:45.729036+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:03:46.853 IST [6349] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:03:46.853 IST [6349] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 11:03:46.853 IST [6349] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$5OltIMQBGbID$8Z6KhDjhtVIbFn+rBf8wFznhV3h3d8xlwG7JLTz/yOM=', NULL, false, 'judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T05:33:46.702275+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:03:47.216 IST [6350] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:03:47.216 IST [6350] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 11:03:47.216 IST [6350] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$5aiSdQOqP9yG$5BOz5UCUw8LMxz14OTBpTp56SZX3ySDn29REoXAvFrA=', NULL, false, 'judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T05:33:47.053097+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:03:58.789 IST [6356] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:03:58.789 IST [6356] DETAIL:  Key (username)=(judson) already exists.
2020-09-27 11:03:58.789 IST [6356] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$nLYB2uetqpEl$Gnds/Dfur4axM1GAAmZXlRLmzSWe9phcwNi0y+q8M8U=', NULL, false, 'judson', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T05:33:58.629212+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:36:05.298 IST [8101] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:36:05.298 IST [8101] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 11:36:05.298 IST [8101] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$uCsm0UILeY7X$OvHiL+N/b0/RzE5W+TRIYlEXSMQnSqbO8Y5fEXgru8g=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:06:05.128524+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:36:21.308 IST [8105] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:36:21.308 IST [8105] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 11:36:21.308 IST [8105] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$IeatZ3AQaju2$S6o5ujyi058tqhdZcEbBFAM3J8obFRsB7GQpg+UVPXU=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:06:21.154056+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:36:22.629 IST [8106] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:36:22.629 IST [8106] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 11:36:22.629 IST [8106] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$hazZozXTc5hX$w53do5Xh4fAdnU3aItqYNb7n1ppg2NnDuyjDZjZYkzg=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:06:22.469978+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:36:23.401 IST [8108] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:36:23.401 IST [8108] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 11:36:23.401 IST [8108] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$o7w1TruhNhyf$Bod/Omaj1rE6AplsSWT0LhwhJxvicd2lia9yFBSaxMs=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:06:23.245986+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:36:24.192 IST [8109] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:36:24.192 IST [8109] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 11:36:24.192 IST [8109] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$cLuQcwreDeiA$6uG4eJsqUl9oXHEhW6PMpp0Adu1c7Qduxayntc4DvM4=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:06:24.039253+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:36:24.552 IST [8110] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:36:24.552 IST [8110] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 11:36:24.552 IST [8110] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$0gYYzhaAqblU$SYH4Bx72pTwr7SO6wkNzKB8qJK3CYcII3+qigPBYJhw=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:06:24.396519+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:36:30.767 IST [8118] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:36:30.767 IST [8118] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 11:36:30.767 IST [8118] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$paGiJxafVsmn$qvk91W3nYpBYW0dTaskIK72ZcYFyXEpWxReEqDCsMKA=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:06:30.611534+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:38:03.483 IST [8161] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:38:03.483 IST [8161] DETAIL:  Key (username)=(admin) already exists.
2020-09-27 11:38:03.483 IST [8161] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$DK00NJY56j6G$rdH5ZaeBwUG8XmiYDwTYGnSjVFwSD+Tgqgyu/sOdJfQ=', NULL, false, 'admin', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T06:08:03.321029+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:38:37.023 IST [8184] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:38:37.023 IST [8184] DETAIL:  Key (username)=(admin) already exists.
2020-09-27 11:38:37.023 IST [8184] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$Yt5ynW6ajZoW$VDJsM/grGZhido6jk5WHk35LiThtBjKM0NEMfTn2gmc=', NULL, false, 'admin', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T06:08:36.863476+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:40:53.943 IST [8269] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:40:53.943 IST [8269] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 11:40:53.943 IST [8269] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$wi4HoXv7miGo$a7B4cjhlzgKwWcZ8v60jJsW/0+HZg4TDZhyPe9dHw8A=', NULL, false, 'judsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T06:10:53.783771+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:42:27.469 IST [8395] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:42:27.469 IST [8395] DETAIL:  Key (username)=(jabajasphin) already exists.
2020-09-27 11:42:27.469 IST [8395] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$suQVp5DIziUi$ob6NlVL8tMtpdTZ+jWFvuGdAVcNq5FfV8mXB2YbOCFg=', NULL, false, 'jabajasphin', '', '', 'jabajasphin@gmail.com', false, true, '2020-09-27T06:12:27.308880+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 11:50:16.881 IST [8537] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 11:50:16.881 IST [8537] DETAIL:  Key (username)=(mynonsuperuser) already exists.
2020-09-27 11:50:16.881 IST [8537] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$3OcPLmNoJluQ$tBIc/zM1Ybhuw7MUFTVgu/rmYYX275ehKHGbxc7SlE8=', NULL, false, 'mynonsuperuser', '', '', 'mynonsuperuser@gmail.com', false, true, '2020-09-27T06:20:16.718188+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 12:00:12.863 IST [8950] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 12:00:12.863 IST [8950] DETAIL:  Key (username)=(mynonsuperuser3) already exists.
2020-09-27 12:00:12.863 IST [8950] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$mTwMsyzZ00pZ$DBJ2eqGCIdP/nK3jcNNDnz4Q4j5T/gV2UVpQWlD1Cl0=', NULL, false, 'mynonsuperuser3', '', '', 'mynonsuperuser3@gmail.com', false, true, '2020-09-27T06:30:12.705738+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 12:55:31.082 IST [18991] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 12:55:31.082 IST [18991] DETAIL:  Key (username)=(ojudsonleo) already exists.
2020-09-27 12:55:31.082 IST [18991] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$I7GxNzPx8hlX$lUMNw0p3ZgAcF6KU7I+k1eel5fk4pULhBO9sX3oBeTY=', NULL, false, 'ojudsonleo', '', '', 'ojudsonleo@gmail.com', false, true, '2020-09-27T07:25:30.928543+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 12:56:49.744 IST [19012] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 12:56:49.744 IST [19012] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 12:56:49.744 IST [19012] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$TZ1lMcQ9ovRG$upQjclq6eL3thUDgDx5YK7ByucNnPDdMpuig/04J79A=', NULL, false, 'judsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T07:26:49.558156+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 12:58:31.027 IST [19033] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 12:58:31.027 IST [19033] DETAIL:  Key (username)=(o.jdsonleo) already exists.
2020-09-27 12:58:31.027 IST [19033] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$GiwGhJqBpR0t$besIa6kqvOweYzH/AQdq731MvRzAXJQmjqYTpeeePfw=', NULL, false, 'o.jdsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T07:28:30.837464+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 12:58:31.117 IST [19034] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 12:58:31.117 IST [19034] DETAIL:  Key (username)=(o.jdsonleo) already exists.
2020-09-27 12:58:31.117 IST [19034] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$toMlyF8PAgpy$nkQt/OqXMch9wV9aupwivDVMC59v8QFptqxquC9t0NA=', NULL, false, 'o.jdsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T07:28:30.940339+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 12:58:32.178 IST [19036] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 12:58:32.178 IST [19036] DETAIL:  Key (username)=(o.jdsonleo) already exists.
2020-09-27 12:58:32.178 IST [19036] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$nN7w6UudEpQp$KrdFI3TibLYV650G7Dvv1KtkF1QSj8F18qqu/PYuGV0=', NULL, false, 'o.jdsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T07:28:32.027680+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 12:59:06.582 IST [19042] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 12:59:06.582 IST [19042] DETAIL:  Key (username)=(String) already exists.
2020-09-27 12:59:06.582 IST [19042] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$2w8ZyQcKzGR7$/II04bkwWr1rBM4ka7hO7Fo/WGbscQu/NiLbVVNd3xA=', NULL, false, 'String', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T07:29:06.424738+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 13:21:16.178 IST [4681] LOG:  received smart shutdown request
2020-09-27 13:21:16.210 IST [4681] LOG:  background worker "logical replication launcher" (PID 4688) exited with exit code 1
2020-09-27 13:21:16.210 IST [4681] LOG:  received SIGHUP, reloading configuration files
2020-09-27 13:21:16.211 IST [4683] LOG:  shutting down
2020-09-27 13:21:16.287 IST [4681] LOG:  database system is shut down
2020-09-27 18:12:36.701 IST [6307] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-27 18:12:36.702 IST [6307] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-27 18:12:36.706 IST [6307] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-27 18:12:36.729 IST [6308] LOG:  database system was shut down at 2020-09-27 13:21:16 IST
2020-09-27 18:12:36.735 IST [6307] LOG:  database system is ready to accept connections
2020-09-27 18:15:41.801 IST [6393] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 18:15:41.801 IST [6393] DETAIL:  Key (username)=(joeljebitto) already exists.
2020-09-27 18:15:41.801 IST [6393] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$9bsIPQBSkrs8$mcJ7+W/FmeM+0h+griLiBum2FbAagNGelzEJHwPXB9A=', NULL, false, 'joeljebitto', '', '', 'joeljebitto@gmail.com', false, true, '2020-09-27T12:45:41.645415+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 18:19:34.557 IST [6500] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:19:34.557 IST [6500] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:19:36.048 IST [6501] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:19:36.048 IST [6501] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:19:36.161 IST [6502] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:19:36.161 IST [6502] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:19:36.696 IST [6503] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:19:36.696 IST [6503] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:19:37.136 IST [6505] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:19:37.136 IST [6505] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:22:06.924 IST [6567] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:22:06.924 IST [6567] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:22:07.696 IST [6568] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:22:07.696 IST [6568] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:22:08.119 IST [6569] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:22:08.119 IST [6569] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:22:08.428 IST [6570] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:22:08.428 IST [6570] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:22:08.716 IST [6571] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:22:08.716 IST [6571] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:22:08.987 IST [6572] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:22:08.987 IST [6572] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:22:09.258 IST [6573] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:22:09.258 IST [6573] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:26:43.656 IST [8543] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:26:43.656 IST [8543] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:26:54.882 IST [8544] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:26:54.882 IST [8544] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:26:55.462 IST [8545] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:26:55.462 IST [8545] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:26:55.660 IST [8546] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:26:55.660 IST [8546] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:26:55.784 IST [8547] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:26:55.784 IST [8547] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:26:55.955 IST [8548] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:26:55.955 IST [8548] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:26:56.337 IST [8549] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:26:56.337 IST [8549] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:13.374 IST [8707] ERROR:  column "locations" of relation "tracks_track" does not exist at character 29
2020-09-27 18:31:13.374 IST [8707] STATEMENT:  INSERT INTO "tracks_track" ("locations", "title", "description", "url", "created_at", "posted_by_id") VALUES ('localhost:3000', 'my_web_site44', 'my web sit44', 'https://google.com', '2020-09-27T13:01:13.374084+00:00'::timestamptz, NULL) RETURNING "tracks_track"."id"
2020-09-27 18:31:40.589 IST [8725] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:40.589 IST [8725] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:41.424 IST [8726] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:41.424 IST [8726] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:41.795 IST [8727] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:41.795 IST [8727] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:42.159 IST [8728] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:42.159 IST [8728] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:42.420 IST [8729] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:42.420 IST [8729] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:42.652 IST [8730] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:42.652 IST [8730] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:42.881 IST [8731] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:42.881 IST [8731] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 18:31:43.137 IST [8733] ERROR:  column tracks_track.locations does not exist at character 29
2020-09-27 18:31:43.137 IST [8733] STATEMENT:  SELECT "tracks_track"."id", "tracks_track"."locations", "tracks_track"."title", "tracks_track"."description", "tracks_track"."url", "tracks_track"."created_at", "tracks_track"."posted_by_id" FROM "tracks_track"
2020-09-27 21:23:24.189 IST [15768] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 21:23:24.189 IST [15768] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 21:23:24.189 IST [15768] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$f8Z9IV9BPZDd$a/TF7pooTq6eaB50tUDbzjKjxNr2ydyRzLpXF5ueyiw=', NULL, false, 'judsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T15:53:23.929231+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 21:23:30.243 IST [15771] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 21:23:30.243 IST [15771] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 21:23:30.243 IST [15771] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$DvhnrFeOyhih$V8DyUV6HmcsVNdTR/ioQhylsNwGV7LkOn+tzI6b1hhg=', NULL, false, 'judsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T15:53:29.975742+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 21:23:31.604 IST [15772] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 21:23:31.604 IST [15772] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 21:23:31.604 IST [15772] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$QtRlSpS3BplE$MuoowtT/2dLyii5hzcobiiVND1JFHU/lusl7FtgWEtM=', NULL, false, 'judsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T15:53:31.338693+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 21:28:41.181 IST [15901] ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
2020-09-27 21:28:41.181 IST [15901] DETAIL:  Key (username)=(judsonleo) already exists.
2020-09-27 21:28:41.181 IST [15901] STATEMENT:  INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$Ubncf11lZ5gl$Q+TITUwL+sTtEEqFLO91URN+v5WN5gFAK+sDdnSoCIs=', NULL, false, 'judsonleo', '', '', 'judsonleo@gmail.com', false, true, '2020-09-27T15:58:41.018415+00:00'::timestamptz) RETURNING "auth_user"."id"
2020-09-27 21:31:00.120 IST [6307] LOG:  received smart shutdown request
2020-09-27 21:31:00.131 IST [6307] LOG:  background worker "logical replication launcher" (PID 6314) exited with exit code 1
2020-09-27 21:31:00.131 IST [6309] LOG:  shutting down
2020-09-27 21:31:00.159 IST [6307] LOG:  database system is shut down
2020-09-28 09:34:59.725 IST [4657] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-28 09:34:59.726 IST [4657] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-28 09:34:59.731 IST [4657] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-28 09:34:59.751 IST [4658] LOG:  database system was shut down at 2020-09-27 21:31:00 IST
2020-09-28 09:34:59.758 IST [4657] LOG:  database system is ready to accept connections
2020-09-28 09:45:45.673 IST [4657] LOG:  received smart shutdown request
2020-09-28 09:45:45.729 IST [4657] LOG:  background worker "logical replication launcher" (PID 4664) exited with exit code 1
2020-09-28 09:45:45.729 IST [4657] LOG:  received SIGHUP, reloading configuration files
2020-09-28 09:45:45.731 IST [4659] LOG:  shutting down
2020-09-28 09:45:45.770 IST [4657] LOG:  database system is shut down
2020-09-29 10:02:31.329 IST [4249] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-29 10:02:31.330 IST [4249] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-29 10:02:31.334 IST [4249] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-29 10:02:31.356 IST [4250] LOG:  database system was shut down at 2020-09-28 09:45:45 IST
2020-09-29 10:02:31.362 IST [4249] LOG:  database system is ready to accept connections
2020-09-29 10:30:30.360 IST [4714] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-29 10:30:30.360 IST [4714] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-29 10:30:30.365 IST [4714] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-29 10:30:30.384 IST [4715] LOG:  database system was interrupted; last known up at 2020-09-29 10:07:31 IST
2020-09-29 10:30:31.292 IST [4715] LOG:  database system was not properly shut down; automatic recovery in progress
2020-09-29 10:30:31.296 IST [4715] LOG:  redo starts at 0/1719CA0
2020-09-29 10:30:31.296 IST [4715] LOG:  invalid record length at 0/1719D88: wanted 24, got 0
2020-09-29 10:30:31.296 IST [4715] LOG:  redo done at 0/1719D50
2020-09-29 10:30:31.317 IST [4714] LOG:  database system is ready to accept connections
2020-09-29 10:57:45.572 IST [7873] FATAL:  lock file "postmaster.pid" already exists
2020-09-29 10:57:45.572 IST [7873] HINT:  Is another postmaster (PID 4714) running in data directory "/home/obedotto/web/mylocal_db"?
2020-09-29 11:50:11.188 IST [4714] LOG:  received smart shutdown request
2020-09-29 11:50:11.206 IST [4714] LOG:  background worker "logical replication launcher" (PID 4721) exited with exit code 1
2020-09-29 11:50:11.206 IST [4716] LOG:  shutting down
2020-09-29 11:50:11.217 IST [4714] LOG:  received SIGHUP, reloading configuration files
2020-09-29 11:50:11.238 IST [4714] LOG:  database system is shut down
2020-09-29 20:10:20.741 IST [8603] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-09-29 20:10:20.742 IST [8603] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-09-29 20:10:20.746 IST [8603] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-29 20:10:20.767 IST [8604] LOG:  database system was shut down at 2020-09-29 11:50:11 IST
2020-09-29 20:10:20.774 IST [8603] LOG:  database system is ready to accept connections
2020-09-29 20:48:35.653 IST [8603] LOG:  received smart shutdown request
2020-09-29 20:48:35.735 IST [8603] LOG:  background worker "logical replication launcher" (PID 8610) exited with exit code 1
2020-09-29 20:48:35.735 IST [8603] LOG:  received SIGHUP, reloading configuration files
2020-09-29 20:48:35.738 IST [8605] LOG:  shutting down
2020-09-29 20:48:35.757 IST [8603] LOG:  database system is shut down
2020-10-01 11:36:37.137 IST [7468] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-10-01 11:36:37.138 IST [7468] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-10-01 11:36:37.142 IST [7468] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-01 11:36:37.168 IST [7469] LOG:  database system was shut down at 2020-09-29 20:48:35 IST
2020-10-01 11:36:37.176 IST [7468] LOG:  database system is ready to accept connections
2020-10-01 11:51:03.652 IST [8545] ERROR:  relation "jobs_jobs" does not exist at character 35
2020-10-01 11:51:03.652 IST [8545] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "jobs_jobs"
2020-10-01 11:51:03.675 IST [8545] ERROR:  relation "jobs_jobs" does not exist at character 54
2020-10-01 11:51:03.675 IST [8545] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 11:51:03.675 IST [8545] ERROR:  relation "jobs_jobs" does not exist at character 54
2020-10-01 11:51:03.675 IST [8545] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 11:51:13.441 IST [8556] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 11:51:13.441 IST [8556] STATEMENT:  INSERT INTO "jobs_jobs" ("username") VALUES ('judsonleo') RETURNING "jobs_jobs"."id"
2020-10-01 11:51:13.458 IST [8556] ERROR:  relation "jobs_jobs" does not exist at character 54
2020-10-01 11:51:13.458 IST [8556] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username" FROM "jobs_jobs"  LIMIT 21
2020-10-01 11:51:18.250 IST [8559] ERROR:  relation "jobs_jobs" does not exist at character 35
2020-10-01 11:51:18.250 IST [8559] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "jobs_jobs"
2020-10-01 11:51:18.268 IST [8559] ERROR:  relation "jobs_jobs" does not exist at character 54
2020-10-01 11:51:18.268 IST [8559] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 11:51:18.268 IST [8559] ERROR:  relation "jobs_jobs" does not exist at character 54
2020-10-01 11:51:18.268 IST [8559] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 11:52:53.620 IST [8605] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 11:52:53.620 IST [8605] STATEMENT:  INSERT INTO "jobs_jobs" ("username", "change_password") VALUES ('judsonleo@user', 'who') RETURNING "jobs_jobs"."id"
2020-10-01 11:52:53.638 IST [8605] ERROR:  relation "jobs_jobs" does not exist at character 85
2020-10-01 11:52:53.638 IST [8605] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username", "jobs_jobs"."change_password" FROM "jobs_jobs"  LIMIT 21
2020-10-01 11:52:59.870 IST [8609] ERROR:  relation "jobs_jobs" does not exist at character 35
2020-10-01 11:52:59.870 IST [8609] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "jobs_jobs"
2020-10-01 11:52:59.889 IST [8609] ERROR:  relation "jobs_jobs" does not exist at character 85
2020-10-01 11:52:59.889 IST [8609] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username", "jobs_jobs"."change_password" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 11:52:59.890 IST [8609] ERROR:  relation "jobs_jobs" does not exist at character 85
2020-10-01 11:52:59.890 IST [8609] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."username", "jobs_jobs"."change_password" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 11:57:46.199 IST [8829] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 11:57:46.199 IST [8829] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float") VALUES ('JobsConfig', 'JobsConfig',  -12.0) RETURNING "jobs_jobs"."id"
2020-10-01 11:57:46.218 IST [8829] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 11:57:46.218 IST [8829] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:02:38.452 IST [9037] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:02:38.452 IST [9037] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float", "Email", "image") VALUES ('JobsConfig', 'JobsConfig',  -211.0, 'ojudsonleo@gmail.com', 'src/Screenshot_from_2020-07-12_12-49-49.png') RETURNING "jobs_jobs"."id"
2020-10-01 12:02:38.473 IST [9037] ERROR:  relation "jobs_jobs" does not exist at character 150
2020-10-01 12:02:38.473 IST [9037] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float", "jobs_jobs"."Email", "jobs_jobs"."image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:03:55.280 IST [9100] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:03:55.280 IST [9100] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float", "Email", "image") VALUES ('JobsConfig', 'JobsConfig',  -211.0, 'ojudsonleo@gmail.com', 'src/user1.jpg') RETURNING "jobs_jobs"."id"
2020-10-01 12:03:55.297 IST [9100] ERROR:  relation "jobs_jobs" does not exist at character 150
2020-10-01 12:03:55.297 IST [9100] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float", "jobs_jobs"."Email", "jobs_jobs"."image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:05:22.737 IST [9167] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:05:22.737 IST [9167] STATEMENT:  INSERT INTO "jobs_jobs" ("Email", "createUser", "change_password", "float", "image") VALUES ('ojudsonleo@gmail.com', 'JobsConfig', 'JobsConfig',  -211.0, 'src/user1_llzAeRf.jpg') RETURNING "jobs_jobs"."id"
2020-10-01 12:05:22.756 IST [9167] ERROR:  relation "jobs_jobs" does not exist at character 150
2020-10-01 12:05:22.756 IST [9167] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."Email", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float", "jobs_jobs"."image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:06:19.799 IST [9211] ERROR:  relation "jobs_jobs" does not exist at character 150
2020-10-01 12:06:19.799 IST [9211] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."Email", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float", "jobs_jobs"."image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:06:32.955 IST [9225] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:06:32.955 IST [9225] STATEMENT:  INSERT INTO "jobs_jobs" ("Email", "createUser", "change_password", "float") VALUES ('ojudsonleo@gmail.com', 'JobsConfig', 'JobsConfig',  -211.0) RETURNING "jobs_jobs"."id"
2020-10-01 12:06:32.973 IST [9225] ERROR:  relation "jobs_jobs" does not exist at character 129
2020-10-01 12:06:32.973 IST [9225] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."Email", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:06:43.201 IST [9242] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:06:43.201 IST [9242] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float", "Email") VALUES ('JobsConfig', 'JobsConfig',  -211.0, 'ojudsonleo@gmail.com') RETURNING "jobs_jobs"."id"
2020-10-01 12:06:43.221 IST [9242] ERROR:  relation "jobs_jobs" does not exist at character 129
2020-10-01 12:06:43.221 IST [9242] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float", "jobs_jobs"."Email" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:06:53.285 IST [9258] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:06:53.285 IST [9258] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float") VALUES ('JobsConfig', 'JobsConfig',  -211.0) RETURNING "jobs_jobs"."id"
2020-10-01 12:06:53.303 IST [9258] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:06:53.303 IST [9258] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:07:29.727 IST [9287] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:07:29.727 IST [9287] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float") VALUES ('JobsConfig', 'JobsConfig',  -211.0) RETURNING "jobs_jobs"."id"
2020-10-01 12:07:29.745 IST [9287] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:07:29.745 IST [9287] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:07:38.327 IST [9300] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:07:38.327 IST [9300] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser") VALUES ('JobsConfig') RETURNING "jobs_jobs"."id"
2020-10-01 12:07:38.345 IST [9300] ERROR:  relation "jobs_jobs" does not exist at character 56
2020-10-01 12:07:38.345 IST [9300] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:07:42.214 IST [9303] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:07:42.214 IST [9303] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser") VALUES ('JobsConfig') RETURNING "jobs_jobs"."id"
2020-10-01 12:07:42.232 IST [9303] ERROR:  relation "jobs_jobs" does not exist at character 56
2020-10-01 12:07:42.232 IST [9303] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:08:25.432 IST [9325] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:08:25.432 IST [9325] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float", "Email") VALUES ('JobsConfig', 'JobsConfig',  -211.0, 'ojudsonleo@gmail.com') RETURNING "jobs_jobs"."id"
2020-10-01 12:08:25.451 IST [9325] ERROR:  relation "jobs_jobs" does not exist at character 129
2020-10-01 12:08:25.451 IST [9325] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float", "jobs_jobs"."Email" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:08:36.520 IST [9339] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:08:36.520 IST [9339] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "float") VALUES ('JobsConfig', 'JobsConfig',  -211.0) RETURNING "jobs_jobs"."id"
2020-10-01 12:08:36.542 IST [9339] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:08:36.542 IST [9339] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."float" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:09:28.257 IST [9367] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:09:28.257 IST [9367] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password") VALUES ('JobsConfig', 'JobsConfig') RETURNING "jobs_jobs"."id"
2020-10-01 12:09:28.278 IST [9367] ERROR:  relation "jobs_jobs" does not exist at character 87
2020-10-01 12:09:28.278 IST [9367] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:24:37.046 IST [10268] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:24:37.046 IST [10268] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "model") VALUES ('JobsConfig', 'JobsConfig', 'rich_editor_M6g0lFr.html') RETURNING "jobs_jobs"."id"
2020-10-01 12:24:37.066 IST [10268] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:24:37.066 IST [10268] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."model" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:25:25.948 IST [10319] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:25:25.948 IST [10319] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "Image") VALUES ('JobsConfig', 'JobsConfig', 'src/user2.jpg') RETURNING "jobs_jobs"."id"
2020-10-01 12:25:25.967 IST [10319] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:25:25.967 IST [10319] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:25:41.052 IST [10352] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:25:41.052 IST [10352] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "Image") VALUES ('JobsConfig', 'JobsConfig', 'user1_hm8EMmi.jpg') RETURNING "jobs_jobs"."id"
2020-10-01 12:25:41.070 IST [10352] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:25:41.070 IST [10352] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:27:23.023 IST [10421] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:27:23.023 IST [10421] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "Image") VALUES ('JobsConfig', 'JobsConfig', 'img/user2.jpg') RETURNING "jobs_jobs"."id"
2020-10-01 12:27:23.042 IST [10421] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:27:23.042 IST [10421] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:30:51.322 IST [10666] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:30:51.322 IST [10666] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "Image") VALUES ('judson', 'Kuttyboy@123', 'local_Storage/Cobweb.png') RETURNING "jobs_jobs"."id"
2020-10-01 12:30:51.341 IST [10666] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:30:51.341 IST [10666] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:31:58.737 IST [10724] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:31:58.737 IST [10724] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "Image") VALUES ('judson', 'Kuttyboy@123', 'Storage/Cobweb.png') RETURNING "jobs_jobs"."id"
2020-10-01 12:31:58.756 IST [10724] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:31:58.756 IST [10724] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:32:32.921 IST [10772] ERROR:  relation "jobs_jobs" does not exist at character 13
2020-10-01 12:32:32.921 IST [10772] STATEMENT:  INSERT INTO "jobs_jobs" ("createUser", "change_password", "Image") VALUES ('judson', 'Kuttyboy@123', 'Storage/Bones.png') RETURNING "jobs_jobs"."id"
2020-10-01 12:32:32.942 IST [10772] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:32:32.942 IST [10772] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs"  LIMIT 21
2020-10-01 12:32:46.002 IST [10797] ERROR:  relation "jobs_jobs" does not exist at character 35
2020-10-01 12:32:46.002 IST [10797] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "jobs_jobs"
2020-10-01 12:32:46.023 IST [10797] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:32:46.023 IST [10797] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 12:32:46.024 IST [10797] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:32:46.024 IST [10797] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 12:33:01.385 IST [10804] ERROR:  relation "jobs_jobs" does not exist at character 35
2020-10-01 12:33:01.385 IST [10804] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "jobs_jobs"
2020-10-01 12:33:01.403 IST [10804] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:33:01.403 IST [10804] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 12:33:01.404 IST [10804] ERROR:  relation "jobs_jobs" does not exist at character 108
2020-10-01 12:33:01.404 IST [10804] STATEMENT:  SELECT "jobs_jobs"."id", "jobs_jobs"."createUser", "jobs_jobs"."change_password", "jobs_jobs"."Image" FROM "jobs_jobs" ORDER BY "jobs_jobs"."id" DESC  LIMIT 21
2020-10-01 12:39:25.845 IST [11107] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:39:25.845 IST [11107] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image", "Email", "IPAddress") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye.png', 'ojudsonleo1@gmail.com', 1090) RETURNING "job_job"."id"
2020-10-01 12:39:25.863 IST [11107] ERROR:  relation "job_job" does not exist at character 142
2020-10-01 12:39:25.863 IST [11107] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image", "job_job"."Email", "job_job"."IPAddress" FROM "job_job"  LIMIT 21
2020-10-01 12:39:26.258 IST [11108] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:39:26.258 IST [11108] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image", "Email", "IPAddress") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye_iwiUSZj.png', 'ojudsonleo1@gmail.com', 1090) RETURNING "job_job"."id"
2020-10-01 12:39:26.284 IST [11108] ERROR:  relation "job_job" does not exist at character 142
2020-10-01 12:39:26.284 IST [11108] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image", "job_job"."Email", "job_job"."IPAddress" FROM "job_job"  LIMIT 21
2020-10-01 12:39:27.722 IST [11109] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:39:27.722 IST [11109] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image", "Email", "IPAddress") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye_pVEHcKP.png', 'ojudsonleo1@gmail.com', 1090) RETURNING "job_job"."id"
2020-10-01 12:39:27.748 IST [11109] ERROR:  relation "job_job" does not exist at character 142
2020-10-01 12:39:27.748 IST [11109] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image", "job_job"."Email", "job_job"."IPAddress" FROM "job_job"  LIMIT 21
2020-10-01 12:39:41.510 IST [11129] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:39:41.510 IST [11129] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye_ntdaLHL.png') RETURNING "job_job"."id"
2020-10-01 12:39:41.540 IST [11129] ERROR:  relation "job_job" does not exist at character 100
2020-10-01 12:39:41.540 IST [11129] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image" FROM "job_job"  LIMIT 21
2020-10-01 12:39:41.945 IST [11130] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:39:41.945 IST [11130] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye_nX6Wh9K.png') RETURNING "job_job"."id"
2020-10-01 12:39:41.975 IST [11130] ERROR:  relation "job_job" does not exist at character 100
2020-10-01 12:39:41.975 IST [11130] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image" FROM "job_job"  LIMIT 21
2020-10-01 12:39:43.309 IST [11131] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:39:43.309 IST [11131] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye_1dJJhU0.png') RETURNING "job_job"."id"
2020-10-01 12:39:43.329 IST [11131] ERROR:  relation "job_job" does not exist at character 100
2020-10-01 12:39:43.329 IST [11131] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image" FROM "job_job"  LIMIT 21
2020-10-01 12:39:50.087 IST [11132] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:39:50.087 IST [11132] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye_qixdTOT.png') RETURNING "job_job"."id"
2020-10-01 12:39:50.108 IST [11132] ERROR:  relation "job_job" does not exist at character 100
2020-10-01 12:39:50.108 IST [11132] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image" FROM "job_job"  LIMIT 21
2020-10-01 12:40:08.369 IST [11151] ERROR:  relation "job_job" does not exist at character 13
2020-10-01 12:40:08.369 IST [11151] STATEMENT:  INSERT INTO "job_job" ("createUser", "change_password", "Image") VALUES ('judson@user2', 'Kuttyboy@123456', 'Storage/Eye_S7SjAas.png') RETURNING "job_job"."id"
2020-10-01 12:40:08.398 IST [11151] ERROR:  relation "job_job" does not exist at character 100
2020-10-01 12:40:08.398 IST [11151] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image" FROM "job_job"  LIMIT 21
2020-10-01 12:44:55.481 IST [7468] LOG:  received smart shutdown request
2020-10-01 12:44:55.537 IST [7468] LOG:  background worker "logical replication launcher" (PID 7475) exited with exit code 1
2020-10-01 12:44:55.537 IST [7468] LOG:  received SIGHUP, reloading configuration files
2020-10-01 12:44:55.539 IST [7470] LOG:  shutting down
2020-10-01 12:44:55.650 IST [7468] LOG:  database system is shut down
2020-10-01 18:11:31.860 IST [4830] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-10-01 18:11:31.860 IST [4830] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-10-01 18:11:31.865 IST [4830] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-01 18:11:31.884 IST [4831] LOG:  database system was shut down at 2020-10-01 12:44:55 IST
2020-10-01 18:11:31.889 IST [4830] LOG:  database system is ready to accept connections
2020-10-01 18:11:51.034 IST [4918] ERROR:  relation "job_job" does not exist at character 35
2020-10-01 18:11:51.034 IST [4918] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "job_job"
2020-10-01 18:11:51.059 IST [4918] ERROR:  relation "job_job" does not exist at character 142
2020-10-01 18:11:51.059 IST [4918] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image", "job_job"."Email", "job_job"."IPAddress" FROM "job_job" ORDER BY "job_job"."id" DESC  LIMIT 21
2020-10-01 18:11:51.059 IST [4918] ERROR:  relation "job_job" does not exist at character 142
2020-10-01 18:11:51.059 IST [4918] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image", "job_job"."Email", "job_job"."IPAddress" FROM "job_job" ORDER BY "job_job"."id" DESC  LIMIT 21
2020-10-01 18:27:41.928 IST [6156] ERROR:  relation "job_job" does not exist at character 35
2020-10-01 18:27:41.928 IST [6156] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "job_job"
2020-10-01 18:27:41.946 IST [6156] ERROR:  relation "job_job" does not exist at character 142
2020-10-01 18:27:41.946 IST [6156] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image", "job_job"."Email", "job_job"."IPAddress" FROM "job_job" ORDER BY "job_job"."id" DESC  LIMIT 21
2020-10-01 18:27:41.947 IST [6156] ERROR:  relation "job_job" does not exist at character 142
2020-10-01 18:27:41.947 IST [6156] STATEMENT:  SELECT "job_job"."id", "job_job"."createUser", "job_job"."change_password", "job_job"."Image", "job_job"."Email", "job_job"."IPAddress" FROM "job_job" ORDER BY "job_job"."id" DESC  LIMIT 21
2020-10-01 18:28:01.672 IST [6166] ERROR:  relation "Blog_blog" does not exist at character 13
2020-10-01 18:28:01.672 IST [6166] STATEMENT:  INSERT INTO "Blog_blog" ("username", "Key") VALUES ('judsonleo@user1', '-=)9hgxh1!vcr3w6$z^5j%c%g)c&lvil^=(5!0!*s!=vqx6ipt') RETURNING "Blog_blog"."id"
2020-10-01 18:28:01.699 IST [6166] ERROR:  relation "Blog_blog" does not exist at character 73
2020-10-01 18:28:01.699 IST [6166] STATEMENT:  SELECT "Blog_blog"."id", "Blog_blog"."username", "Blog_blog"."Key" FROM "Blog_blog"  LIMIT 21
2020-10-01 18:53:49.259 IST [7533] ERROR:  relation "Blog_blog" does not exist at character 13
2020-10-01 18:53:49.259 IST [7533] STATEMENT:  INSERT INTO "Blog_blog" ("username", "Email_an_image", "BASE_DIR", "SECRET_KEY", "DEBUG", "ALLOWED_HOSTS", "INSTALLED_APPS", "MIDDLEWARE", "ROOT_URLCONF", "TEMPLATES", "WSGI_APPLICATION", "DATABASES", "AUTH_PASSWORD_VALIDATORS", "LANGUAGE_CODE", "TIME_ZONE", "USE_I18N", "USE_L10N", "USE_TZ", "STATIC_URL", "MEDIA_ROOT", "MEDIA_URL") VALUES ('judsonleo@user2', 'Storage/Cobweb.png', 'os.path.dirname(os.path.dirname(os.path.abspath))', '''-=)9hgxh1!vcr3w6$z^5j%c%g)c&lvil^=(5!0!*s!=vqx6ipt''', 'True', '[]', '''django.contrib.admin'',
		''django.contrib.auth'',
		''django.contrib.contenttypes'',
		''django.contrib.sessions'',
		''django.contrib.messages'',
	       ''django.contrib.staticfiles'',', '''django.middleware.security.SecurityMiddleware'',
		''django.contrib.sessions.middleware.SessionMiddleware'',
		''django.middleware.common.CommonMiddleware'',
		''django.middleware.csrf.CsrfViewMiddleware'',
		''django.contrib.auth.middleware.AuthenticationMiddleware'',
		''django.contrib.messages.middleware.MessageMiddleware'',
	''django.middleware.clickjacking.XFrameOptionsMiddleware'',', 'app.urls', '{
			''BACKEND'': ''django.template.backends.django.DjangoTemplates'',
			''DIRS'': [],
			''APP_DIRS'': True,
			''OPTIONS'': {
				''context_processors'': [
					''django.template.context_processors.debug'',
					''django.template.context_processors.request'',
					''django.contrib.auth.context_processors.auth'',
					''django.contrib.messages.context_processors.messages'',
				],
			},
	},', 'app.wsgi.appliction', '''default'': {
			''ENGINE'': ''django.db.backends.postgresql'',
			''NAME'': ''test'',
			''USER'': ''Joel'',
			''PASSWORD'': ''12345'',
			''HOST'': ''localhost'',
			''PORT'': '''',
	}', '{
			''NAME'': ''django.contrib.auth.password_validation.UserAttributeSimilarityValidator'',
		},
		{
			''NAME'': ''django.contrib.auth.password_validation.MinimumLengthValidator'',
		},
		{
			''NAME'': ''django.contrib.auth.password_validation.CommonPasswordValidator'',
		},
		{
			''NAME'': ''django.contrib.auth.password_validation.NumericPasswordValidator'',
	},', '''en-us''', '''UTC''', 'True', 'True', 'True', '''/static/''', 'os.path.join(BASE_DIR, ''src'')', '''/src/''') RETURNING "Blog_blog"."id"
2020-10-01 18:53:49.277 IST [7533] ERROR:  relation "Blog_blog" does not exist at character 591
2020-10-01 18:53:49.277 IST [7533] STATEMENT:  SELECT "Blog_blog"."id", "Blog_blog"."username", "Blog_blog"."Email_an_image", "Blog_blog"."BASE_DIR", "Blog_blog"."SECRET_KEY", "Blog_blog"."DEBUG", "Blog_blog"."ALLOWED_HOSTS", "Blog_blog"."INSTALLED_APPS", "Blog_blog"."MIDDLEWARE", "Blog_blog"."ROOT_URLCONF", "Blog_blog"."TEMPLATES", "Blog_blog"."WSGI_APPLICATION", "Blog_blog"."DATABASES", "Blog_blog"."AUTH_PASSWORD_VALIDATORS", "Blog_blog"."LANGUAGE_CODE", "Blog_blog"."TIME_ZONE", "Blog_blog"."USE_I18N", "Blog_blog"."USE_L10N", "Blog_blog"."USE_TZ", "Blog_blog"."STATIC_URL", "Blog_blog"."MEDIA_ROOT", "Blog_blog"."MEDIA_URL" FROM "Blog_blog"  LIMIT 21
2020-10-01 19:06:17.851 IST [8114] ERROR:  relation "Blog_blog" does not exist at character 13
2020-10-01 19:06:17.851 IST [8114] STATEMENT:  INSERT INTO "Blog_blog" ("username", "Email_an_image", "BASE_DIR", "SECRET_KEY", "DEBUG", "ALLOWED_HOSTS", "INSTALLED_APPS", "GRAPHENE", "MIDDLEWARE", "CORS_ORIGIN_ALLOW_ALL", "AUTHENTICATION_BACKENDS", "ROOT_URLCONF", "TEMPLATES", "WSGI_APPLICATION", "DATABASES", "AUTH_PASSWORD_VALIDATORS", "LANGUAGE_CODE", "TIME_ZONE", "USE_I18N", "USE_L10N", "USE_TZ", "STATIC_URL", "MEDIA_ROOT", "MEDIA_URL") VALUES ('judsonleo@user5', 'Storage/Dracula.png', 'os.path.dirname(os.path.dirname(os.path.abspath))', '''@54_@_^f10dw2=@h810l3r*=!+-lwvi^b2yk)sso!#+m1&)@@t''', 'True', '["*"]', '''corsheaders'',
	    ''django.contrib.admin'',
	    ''django.contrib.auth'',
	    ''django.contrib.contenttypes'',
	    ''django.contrib.sessions'',
	    ''django.contrib.messages'',
	    ''django.contrib.staticfiles'',
	    ''graphene_django'',
	    ''tracks'',
	    ''job.apps.JobConfig'',
	    ''Blog.apps.BlogConfig''', '''SCHEMA'': "app.schema.schema",
	    ''MIDDLEWARE'': [
	        ''graphql_jwt.middleware.JSONWebTokenMiddleware'',
	    ],', '''corsheaders.middleware.CorsMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.security.SecurityMiddleware'',
	    ''django.contrib.sessions.middleware.SessionMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.csrf.CsrfViewMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',
	    ''django.contrib.messages.middleware.MessageMiddleware'',
	    ''django.middleware.clickjacking.XFrameOptionsMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',', 'True', '''graphql_jwt.backends.JSONWebTokenBackend'',
	    ''django.contrib.auth.backends.ModelBackend''', 'app.urls', '{
	        ''BACKEND'': ''django.template.backends.django.DjangoTemplates'',
	        ''DIRS'': [],
	        ''APP_DIRS'': True,
	        ''OPTIONS'': {
	            ''context_processors'': [
	                ''django.template.context_processors.debug'',
	                ''django.template.context_processors.request'',
	                ''django.contrib.auth.context_processors.auth'',
	                ''django.contrib.messages.context_processors.messages'',
	            ],
	        },
	    },', '''app.wsgi.application''', '''default'': {
	        ''ENGINE'': ''django.db.backends.postgresql'',
	        ''NAME'': ''db'',
	        ''USER'': ''mynonsuperuser'',
	        ''PASSWORD'': ''12345'',
	        ''HOST'': ''localhost'',
	        ''PORT'': '''',
	    }', '{
	        ''NAME'': ''django.contrib.auth.password_validation.UserAttributeSimilarityValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.MinimumLengthValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.CommonPasswordValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.NumericPasswordValidator'',
	    },', '''en-us''', '''UTC''', 'True', 'True', 'True', '''/static/''', 'os.path.join(BASE_DIR, ''src'')', '''/src/''') RETURNING "Blog_blog"."id"
2020-10-01 19:06:17.874 IST [8114] ERROR:  relation "Blog_blog" does not exist at character 691
2020-10-01 19:06:17.874 IST [8114] STATEMENT:  SELECT "Blog_blog"."id", "Blog_blog"."username", "Blog_blog"."Email_an_image", "Blog_blog"."BASE_DIR", "Blog_blog"."SECRET_KEY", "Blog_blog"."DEBUG", "Blog_blog"."ALLOWED_HOSTS", "Blog_blog"."INSTALLED_APPS", "Blog_blog"."GRAPHENE", "Blog_blog"."MIDDLEWARE", "Blog_blog"."CORS_ORIGIN_ALLOW_ALL", "Blog_blog"."AUTHENTICATION_BACKENDS", "Blog_blog"."ROOT_URLCONF", "Blog_blog"."TEMPLATES", "Blog_blog"."WSGI_APPLICATION", "Blog_blog"."DATABASES", "Blog_blog"."AUTH_PASSWORD_VALIDATORS", "Blog_blog"."LANGUAGE_CODE", "Blog_blog"."TIME_ZONE", "Blog_blog"."USE_I18N", "Blog_blog"."USE_L10N", "Blog_blog"."USE_TZ", "Blog_blog"."STATIC_URL", "Blog_blog"."MEDIA_ROOT", "Blog_blog"."MEDIA_URL" FROM "Blog_blog"  LIMIT 21
2020-10-01 19:06:17.972 IST [8116] ERROR:  relation "Blog_blog" does not exist at character 13
2020-10-01 19:06:17.972 IST [8116] STATEMENT:  INSERT INTO "Blog_blog" ("username", "Email_an_image", "BASE_DIR", "SECRET_KEY", "DEBUG", "ALLOWED_HOSTS", "INSTALLED_APPS", "GRAPHENE", "MIDDLEWARE", "CORS_ORIGIN_ALLOW_ALL", "AUTHENTICATION_BACKENDS", "ROOT_URLCONF", "TEMPLATES", "WSGI_APPLICATION", "DATABASES", "AUTH_PASSWORD_VALIDATORS", "LANGUAGE_CODE", "TIME_ZONE", "USE_I18N", "USE_L10N", "USE_TZ", "STATIC_URL", "MEDIA_ROOT", "MEDIA_URL") VALUES ('judsonleo@user5', 'Storage/Dracula_aqx8rVI.png', 'os.path.dirname(os.path.dirname(os.path.abspath))', '''@54_@_^f10dw2=@h810l3r*=!+-lwvi^b2yk)sso!#+m1&)@@t''', 'True', '["*"]', '''corsheaders'',
	    ''django.contrib.admin'',
	    ''django.contrib.auth'',
	    ''django.contrib.contenttypes'',
	    ''django.contrib.sessions'',
	    ''django.contrib.messages'',
	    ''django.contrib.staticfiles'',
	    ''graphene_django'',
	    ''tracks'',
	    ''job.apps.JobConfig'',
	    ''Blog.apps.BlogConfig''', '''SCHEMA'': "app.schema.schema",
	    ''MIDDLEWARE'': [
	        ''graphql_jwt.middleware.JSONWebTokenMiddleware'',
	    ],', '''corsheaders.middleware.CorsMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.security.SecurityMiddleware'',
	    ''django.contrib.sessions.middleware.SessionMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.csrf.CsrfViewMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',
	    ''django.contrib.messages.middleware.MessageMiddleware'',
	    ''django.middleware.clickjacking.XFrameOptionsMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',', 'True', '''graphql_jwt.backends.JSONWebTokenBackend'',
	    ''django.contrib.auth.backends.ModelBackend''', 'app.urls', '{
	        ''BACKEND'': ''django.template.backends.django.DjangoTemplates'',
	        ''DIRS'': [],
	        ''APP_DIRS'': True,
	        ''OPTIONS'': {
	            ''context_processors'': [
	                ''django.template.context_processors.debug'',
	                ''django.template.context_processors.request'',
	                ''django.contrib.auth.context_processors.auth'',
	                ''django.contrib.messages.context_processors.messages'',
	            ],
	        },
	    },', '''app.wsgi.application''', '''default'': {
	        ''ENGINE'': ''django.db.backends.postgresql'',
	        ''NAME'': ''db'',
	        ''USER'': ''mynonsuperuser'',
	        ''PASSWORD'': ''12345'',
	        ''HOST'': ''localhost'',
	        ''PORT'': '''',
	    }', '{
	        ''NAME'': ''django.contrib.auth.password_validation.UserAttributeSimilarityValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.MinimumLengthValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.CommonPasswordValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.NumericPasswordValidator'',
	    },', '''en-us''', '''UTC''', 'True', 'True', 'True', '''/static/''', 'os.path.join(BASE_DIR, ''src'')', '''/src/''') RETURNING "Blog_blog"."id"
2020-10-01 19:06:18.000 IST [8116] ERROR:  relation "Blog_blog" does not exist at character 691
2020-10-01 19:06:18.000 IST [8116] STATEMENT:  SELECT "Blog_blog"."id", "Blog_blog"."username", "Blog_blog"."Email_an_image", "Blog_blog"."BASE_DIR", "Blog_blog"."SECRET_KEY", "Blog_blog"."DEBUG", "Blog_blog"."ALLOWED_HOSTS", "Blog_blog"."INSTALLED_APPS", "Blog_blog"."GRAPHENE", "Blog_blog"."MIDDLEWARE", "Blog_blog"."CORS_ORIGIN_ALLOW_ALL", "Blog_blog"."AUTHENTICATION_BACKENDS", "Blog_blog"."ROOT_URLCONF", "Blog_blog"."TEMPLATES", "Blog_blog"."WSGI_APPLICATION", "Blog_blog"."DATABASES", "Blog_blog"."AUTH_PASSWORD_VALIDATORS", "Blog_blog"."LANGUAGE_CODE", "Blog_blog"."TIME_ZONE", "Blog_blog"."USE_I18N", "Blog_blog"."USE_L10N", "Blog_blog"."USE_TZ", "Blog_blog"."STATIC_URL", "Blog_blog"."MEDIA_ROOT", "Blog_blog"."MEDIA_URL" FROM "Blog_blog"  LIMIT 21
2020-10-01 19:21:10.359 IST [9408] ERROR:  relation "setting_setting" does not exist at character 13
2020-10-01 19:21:10.359 IST [9408] STATEMENT:  INSERT INTO "setting_setting" ("token", "username", "Email_an_image", "BASE_DIR", "SECRET_KEY", "DEBUG", "ALLOWED_HOSTS", "INSTALLED_APPS", "GRAPHENE", "MIDDLEWARE", "CORS_ORIGIN_ALLOW_ALL", "AUTHENTICATION_BACKENDS", "ROOT_URLCONF", "TEMPLATES", "WSGI_APPLICATION", "DATABASES", "AUTH_PASSWORD_VALIDATORS", "LANGUAGE_CODE", "TIME_ZONE", "USE_I18N", "USE_L10N", "USE_TZ", "STATIC_URL", "MEDIA_ROOT", "MEDIA_URL") VALUES ('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Imp1ZHNvbiIsImV4cCI6MTYwMTU2MDI3Niwib3JpZ0lhdCI6MTYwMTU1OTk3Nn0.3ib8GUyN130x36fP6O7VQFJSyi21UzJIbb3TvwiAhRY', 'judson1', 'Storage/Skull.png', 'os.path.dirname(os.path.dirname(os.path.abspath))', '''@54_@_^f10dw2=@h810l3r*=!+-lwvi^b2yk)sso!#+m1&)@@t''', 'True', '["*"]', '''corsheaders'',
	    ''django.contrib.admin'',
	    ''django.contrib.auth'',
	    ''django.contrib.contenttypes'',
	    ''django.contrib.sessions'',
	    ''django.contrib.messages'',
	    ''django.contrib.staticfiles'',
	    ''graphene_django'',
	    ''tracks'',
	    ''job.apps.JobConfig'',
	    ''setting.apps.settingConfig''', '''SCHEMA'': "app.schema.schema",
	    ''MIDDLEWARE'': [
	        ''graphql_jwt.middleware.JSONWebTokenMiddleware'',
	    ],', '''corsheaders.middleware.CorsMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.security.SecurityMiddleware'',
	    ''django.contrib.sessions.middleware.SessionMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.csrf.CsrfViewMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',
	    ''django.contrib.messages.middleware.MessageMiddleware'',
	    ''django.middleware.clickjacking.XFrameOptionsMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',', 'True', '''graphql_jwt.backends.JSONWebTokenBackend'',
	    ''django.contrib.auth.backends.ModelBackend'',', 'app.urls', '{
	        ''BACKEND'': ''django.template.backends.django.DjangoTemplates'',
	        ''DIRS'': [],
	        ''APP_DIRS'': True,
	        ''OPTIONS'': {
	            ''context_processors'': [
	                ''django.template.context_processors.debug'',
	                ''django.template.context_processors.request'',
	                ''django.contrib.auth.context_processors.auth'',
	                ''django.contrib.messages.context_processors.messages'',
	            ],
	        },
	    },', '''app.wsgi.application''', '''default'': {
	        ''ENGINE'': ''django.db.backends.postgresql'',
	        ''NAME'': ''db'',
	        ''USER'': ''mynonsuperuser'',
	        ''PASSWORD'': ''12345'',
	        ''HOST'': ''localhost'',
	        ''PORT'': '''',
	    }', '{
	        ''NAME'': ''django.contrib.auth.password_validation.UserAttributeSimilarityValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.MinimumLengthValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.CommonPasswordValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.NumericPasswordValidator'',
	    },', '''en-us''', '''UTC''', 'True', 'True', 'True', '/static/', 'os.path.join(os.path.dirname(BASE_DIR), "src")', '/src/') RETURNING "setting_setting"."id"
2020-10-01 19:21:10.383 IST [9408] ERROR:  relation "setting_setting" does not exist at character 868
2020-10-01 19:21:10.383 IST [9408] STATEMENT:  SELECT "setting_setting"."id", "setting_setting"."token", "setting_setting"."username", "setting_setting"."Email_an_image", "setting_setting"."BASE_DIR", "setting_setting"."SECRET_KEY", "setting_setting"."DEBUG", "setting_setting"."ALLOWED_HOSTS", "setting_setting"."INSTALLED_APPS", "setting_setting"."GRAPHENE", "setting_setting"."MIDDLEWARE", "setting_setting"."CORS_ORIGIN_ALLOW_ALL", "setting_setting"."AUTHENTICATION_BACKENDS", "setting_setting"."ROOT_URLCONF", "setting_setting"."TEMPLATES", "setting_setting"."WSGI_APPLICATION", "setting_setting"."DATABASES", "setting_setting"."AUTH_PASSWORD_VALIDATORS", "setting_setting"."LANGUAGE_CODE", "setting_setting"."TIME_ZONE", "setting_setting"."USE_I18N", "setting_setting"."USE_L10N", "setting_setting"."USE_TZ", "setting_setting"."STATIC_URL", "setting_setting"."MEDIA_ROOT", "setting_setting"."MEDIA_URL" FROM "setting_setting"  LIMIT 21
2020-10-01 19:22:15.994 IST [9445] ERROR:  relation "setting_setting" does not exist at character 13
2020-10-01 19:22:15.994 IST [9445] STATEMENT:  INSERT INTO "setting_setting" ("token", "username", "Email_an_image", "BASE_DIR", "SECRET_KEY", "DEBUG", "ALLOWED_HOSTS", "INSTALLED_APPS", "GRAPHENE", "MIDDLEWARE", "CORS_ORIGIN_ALLOW_ALL", "AUTHENTICATION_BACKENDS", "ROOT_URLCONF", "TEMPLATES", "WSGI_APPLICATION", "DATABASES", "AUTH_PASSWORD_VALIDATORS", "LANGUAGE_CODE", "TIME_ZONE", "USE_I18N", "USE_L10N", "USE_TZ", "STATIC_URL", "MEDIA_ROOT", "MEDIA_URL") VALUES ('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Imp1ZHNvbiIsImV4cCI6MTYwMTU2MDI3Niwib3JpZ0lhdCI6MTYwMTU1OTk3Nn0.3ib8GUyN130x36fP6O7VQFJSyi21UzJIbb3TvwiAhRY', 'judson1', 'data/Skull.png', 'os.path.dirname(os.path.dirname(os.path.abspath))', '''@54_@_^f10dw2=@h810l3r*=!+-lwvi^b2yk)sso!#+m1&)@@t''', 'True', '["*"]', '''corsheaders'',
	    ''django.contrib.admin'',
	    ''django.contrib.auth'',
	    ''django.contrib.contenttypes'',
	    ''django.contrib.sessions'',
	    ''django.contrib.messages'',
	    ''django.contrib.staticfiles'',
	    ''graphene_django'',
	    ''tracks'',
	    ''job.apps.JobConfig'',
	    ''setting.apps.settingConfig''', '''SCHEMA'': "app.schema.schema",
	    ''MIDDLEWARE'': [
	        ''graphql_jwt.middleware.JSONWebTokenMiddleware'',
	    ],', '''corsheaders.middleware.CorsMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.security.SecurityMiddleware'',
	    ''django.contrib.sessions.middleware.SessionMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.csrf.CsrfViewMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',
	    ''django.contrib.messages.middleware.MessageMiddleware'',
	    ''django.middleware.clickjacking.XFrameOptionsMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',', 'True', '''graphql_jwt.backends.JSONWebTokenBackend'',
	    ''django.contrib.auth.backends.ModelBackend'',', 'app.urls', '{
	        ''BACKEND'': ''django.template.backends.django.DjangoTemplates'',
	        ''DIRS'': [],
	        ''APP_DIRS'': True,
	        ''OPTIONS'': {
	            ''context_processors'': [
	                ''django.template.context_processors.debug'',
	                ''django.template.context_processors.request'',
	                ''django.contrib.auth.context_processors.auth'',
	                ''django.contrib.messages.context_processors.messages'',
	            ],
	        },
	    },', '''app.wsgi.application''', '''default'': {
	        ''ENGINE'': ''django.db.backends.postgresql'',
	        ''NAME'': ''db'',
	        ''USER'': ''mynonsuperuser'',
	        ''PASSWORD'': ''12345'',
	        ''HOST'': ''localhost'',
	        ''PORT'': '''',
	    }', '{
	        ''NAME'': ''django.contrib.auth.password_validation.UserAttributeSimilarityValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.MinimumLengthValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.CommonPasswordValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.NumericPasswordValidator'',
	    },', '''en-us''', '''UTC''', 'True', 'True', 'True', '/static/', 'os.path.join(os.path.dirname(BASE_DIR), "src")', '/src/') RETURNING "setting_setting"."id"
2020-10-01 19:22:16.023 IST [9445] ERROR:  relation "setting_setting" does not exist at character 868
2020-10-01 19:22:16.023 IST [9445] STATEMENT:  SELECT "setting_setting"."id", "setting_setting"."token", "setting_setting"."username", "setting_setting"."Email_an_image", "setting_setting"."BASE_DIR", "setting_setting"."SECRET_KEY", "setting_setting"."DEBUG", "setting_setting"."ALLOWED_HOSTS", "setting_setting"."INSTALLED_APPS", "setting_setting"."GRAPHENE", "setting_setting"."MIDDLEWARE", "setting_setting"."CORS_ORIGIN_ALLOW_ALL", "setting_setting"."AUTHENTICATION_BACKENDS", "setting_setting"."ROOT_URLCONF", "setting_setting"."TEMPLATES", "setting_setting"."WSGI_APPLICATION", "setting_setting"."DATABASES", "setting_setting"."AUTH_PASSWORD_VALIDATORS", "setting_setting"."LANGUAGE_CODE", "setting_setting"."TIME_ZONE", "setting_setting"."USE_I18N", "setting_setting"."USE_L10N", "setting_setting"."USE_TZ", "setting_setting"."STATIC_URL", "setting_setting"."MEDIA_ROOT", "setting_setting"."MEDIA_URL" FROM "setting_setting"  LIMIT 21
2020-10-01 19:25:41.976 IST [9566] ERROR:  relation "setting_setting" does not exist at character 13
2020-10-01 19:25:41.976 IST [9566] STATEMENT:  INSERT INTO "setting_setting" ("token", "username", "Email_an_image", "BASE_DIR", "SECRET_KEY", "DEBUG", "ALLOWED_HOSTS", "INSTALLED_APPS", "GRAPHENE", "MIDDLEWARE", "CORS_ORIGIN_ALLOW_ALL", "AUTHENTICATION_BACKENDS", "ROOT_URLCONF", "TEMPLATES", "WSGI_APPLICATION", "DATABASES", "AUTH_PASSWORD_VALIDATORS", "LANGUAGE_CODE", "TIME_ZONE", "USE_I18N", "USE_L10N", "USE_TZ", "STATIC_URL", "MEDIA_ROOT", "MEDIA_URL") VALUES ('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Imp1ZHNvbiIsImV4cCI6MTYwMTU2MDI3Niwib3JpZ0lhdCI6MTYwMTU1OTk3Nn0.3ib8GUyN130x36fP6O7VQFJSyi21UzJIbb3TvwiAhRY', 'judson2', 'data/Bat.png', 'os.path.dirname(os.path.dirname(os.path.abspath))', '''@54_@_^f10dw2=@h810l3r*=!+-lwvi^b2yk)sso!#+m1&)@@t''', 'True', '[""]', '''corsheaders'',
	    ''django.contrib.admin'',
	    ''django.contrib.auth'',
	    ''django.contrib.contenttypes'',
	    ''django.contrib.sessions'',
	    ''django.contrib.messages'',
	    ''django.contrib.staticfiles'',
	    ''graphene_django'',
	    ''tracks'',
	    ''job.apps.JobConfig'',
	    ''setting.apps.settingConfig''', '''SCHEMA'': "app.schema.schema",
	    ''MIDDLEWARE'': [
	        ''graphql_jwt.middleware.JSONWebTokenMiddleware'',
	    ],', '''corsheaders.middleware.CorsMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.security.SecurityMiddleware'',
	    ''django.contrib.sessions.middleware.SessionMiddleware'',
	    ''django.middleware.common.CommonMiddleware'',
	    ''django.middleware.csrf.CsrfViewMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',
	    ''django.contrib.messages.middleware.MessageMiddleware'',
	    ''django.middleware.clickjacking.XFrameOptionsMiddleware'',
	    ''django.contrib.auth.middleware.AuthenticationMiddleware'',', 'True', '''graphql_jwt.backends.JSONWebTokenBackend'',
	''django.contrib.auth.backends.ModelBackend'',', 'app.urls', '{
	        ''BACKEND'': ''django.template.backends.django.DjangoTemplates'',
	        ''DIRS'': [],
	        ''APP_DIRS'': True,
	        ''OPTIONS'': {
	            ''context_processors'': [
	                ''django.template.context_processors.debug'',
	                ''django.template.context_processors.request'',
	                ''django.contrib.auth.context_processors.auth'',
	                ''django.contrib.messages.context_processors.messages'',
	            ],
	        },
	    },', 'app.wsgi.application', '''default'': {
	        ''ENGINE'': ''django.db.backends.postgresql'',
	        ''NAME'': ''db'',
	        ''USER'': ''mynonsuperuser'',
	        ''PASSWORD'': ''12345'',
	        ''HOST'': ''localhost'',
	        ''PORT'': '''',
	    }', '{
	        ''NAME'': ''django.contrib.auth.password_validation.UserAttributeSimilarityValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.MinimumLengthValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.CommonPasswordValidator'',
	    },
	    {
	        ''NAME'': ''django.contrib.auth.password_validation.NumericPasswordValidator'',
	    },', 'en-us', '''UTC''', 'True', 'True', 'True', '''/static/''', 'os.path.join(os.path.dirname(BASE_DIR), "src")', '''/src/''') RETURNING "setting_setting"."id"
2020-10-01 19:25:41.997 IST [9566] ERROR:  relation "setting_setting" does not exist at character 868
2020-10-01 19:25:41.997 IST [9566] STATEMENT:  SELECT "setting_setting"."id", "setting_setting"."token", "setting_setting"."username", "setting_setting"."Email_an_image", "setting_setting"."BASE_DIR", "setting_setting"."SECRET_KEY", "setting_setting"."DEBUG", "setting_setting"."ALLOWED_HOSTS", "setting_setting"."INSTALLED_APPS", "setting_setting"."GRAPHENE", "setting_setting"."MIDDLEWARE", "setting_setting"."CORS_ORIGIN_ALLOW_ALL", "setting_setting"."AUTHENTICATION_BACKENDS", "setting_setting"."ROOT_URLCONF", "setting_setting"."TEMPLATES", "setting_setting"."WSGI_APPLICATION", "setting_setting"."DATABASES", "setting_setting"."AUTH_PASSWORD_VALIDATORS", "setting_setting"."LANGUAGE_CODE", "setting_setting"."TIME_ZONE", "setting_setting"."USE_I18N", "setting_setting"."USE_L10N", "setting_setting"."USE_TZ", "setting_setting"."STATIC_URL", "setting_setting"."MEDIA_ROOT", "setting_setting"."MEDIA_URL" FROM "setting_setting"  LIMIT 21
2020-10-01 20:42:02.226 IST [4830] LOG:  received smart shutdown request
2020-10-01 20:42:02.243 IST [4830] LOG:  background worker "logical replication launcher" (PID 4837) exited with exit code 1
2020-10-01 20:42:02.243 IST [4830] LOG:  received SIGHUP, reloading configuration files
2020-10-01 20:42:02.243 IST [4832] LOG:  shutting down
2020-10-01 20:42:02.290 IST [4830] LOG:  database system is shut down
2020-10-03 11:16:25.128 IST [7473] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-10-03 11:16:25.129 IST [7473] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-10-03 11:16:25.133 IST [7473] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-03 11:16:25.152 IST [7474] LOG:  database system was shut down at 2020-10-01 20:42:02 IST
2020-10-03 11:16:25.158 IST [7473] LOG:  database system is ready to accept connections
2020-10-03 11:29:49.989 IST [7473] LOG:  received smart shutdown request
2020-10-03 11:29:50.034 IST [7473] LOG:  background worker "logical replication launcher" (PID 7480) exited with exit code 1
2020-10-03 11:29:50.034 IST [7475] LOG:  shutting down
2020-10-03 11:29:50.036 IST [7473] LOG:  received SIGHUP, reloading configuration files
2020-10-03 11:29:50.094 IST [7473] LOG:  database system is shut down
2020-10-07 14:36:03.007 IST [5625] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-10-07 14:36:03.008 IST [5625] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-10-07 14:36:03.013 IST [5625] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-07 14:36:03.036 IST [5626] LOG:  database system was shut down at 2020-10-03 11:29:50 IST
2020-10-07 14:36:03.041 IST [5625] LOG:  database system is ready to accept connections
2020-10-07 14:46:14.393 IST [6776] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:46:14.393 IST [6776] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:46:20.056 IST [6781] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:46:20.056 IST [6781] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:46:21.819 IST [6786] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:46:21.819 IST [6786] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:46:23.555 IST [6793] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:46:23.555 IST [6793] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:46:24.331 IST [6798] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:46:24.331 IST [6798] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:46:35.090 IST [7384] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:46:35.090 IST [7384] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:46:40.873 IST [7390] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:46:40.873 IST [7390] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:12.364 IST [7992] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:12.364 IST [7992] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:14.378 IST [7996] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:14.378 IST [7996] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:14.995 IST [8000] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:14.995 IST [8000] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:15.575 IST [8004] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:15.575 IST [8004] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:16.198 IST [8008] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:16.198 IST [8008] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:16.740 IST [8012] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:16.740 IST [8012] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:17.240 IST [8016] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:17.240 IST [8016] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:17.997 IST [8020] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:17.997 IST [8020] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:20.233 IST [8024] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:20.233 IST [8024] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:21.461 IST [8028] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:21.461 IST [8028] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 14:47:22.487 IST [8032] FATAL:  lock file "postmaster.pid" already exists
2020-10-07 14:47:22.487 IST [8032] HINT:  Is another postmaster (PID 5625) running in data directory "/home/obedotto/web/mylocal_db"?
2020-10-07 16:33:52.145 IST [5625] LOG:  background worker "logical replication launcher" (PID 5632) exited with exit code 1
2020-10-07 16:33:52.146 IST [5625] LOG:  received smart shutdown request
2020-10-07 16:33:52.153 IST [5627] LOG:  shutting down
2020-10-07 16:33:52.173 IST [5625] LOG:  received SIGHUP, reloading configuration files
2020-10-07 16:33:52.189 IST [5625] LOG:  database system is shut down
2020-10-08 10:00:29.052 IST [2801] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.23.0.449-a04d0) 7.3.0, 64-bit
2020-10-08 10:00:29.052 IST [2801] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-10-08 10:00:29.057 IST [2801] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-08 10:00:29.080 IST [2802] LOG:  database system was shut down at 2020-10-07 16:33:52 IST
2020-10-08 10:00:29.086 IST [2801] LOG:  database system is ready to accept connections
2020-10-08 12:41:42.208 IST [2801] LOG:  received smart shutdown request
2020-10-08 12:41:42.225 IST [2801] LOG:  background worker "logical replication launcher" (PID 2808) exited with exit code 1
2020-10-08 12:41:42.225 IST [2801] LOG:  received SIGHUP, reloading configuration files
2020-10-08 12:41:42.227 IST [2803] LOG:  shutting down
2020-10-08 12:41:42.251 IST [2801] LOG:  database system is shut down
